-- uncatalog ALL

uncatalog db DB_DEVLA;
uncatalog db DB_DEVLI;
uncatalog db DB_DEVOA;
uncatalog db DB_DV3AD;
uncatalog db DB_DV3CP;
uncatalog db DB_DV3EA;
uncatalog db DB_DV3LE;
uncatalog db DB_DV3SM;
uncatalog db DB_DV3TD;
uncatalog db DB_DV3UA;
uncatalog db DB_ECLD;
uncatalog db DB_ECLI; 
uncatalog db DB_ECLP; 
uncatalog db DB_ECLR;
uncatalog db DB_ECLS2;
uncatalog db DB_ECLS3;
uncatalog db DB_INTAD;
uncatalog db DB_INTCP;
uncatalog db DB_INTEA;
uncatalog db DB_INTGA;
uncatalog db DB_INTGI;
uncatalog db DB_INTLE;
uncatalog db DB_INTOA;
uncatalog db DB_INTSM;
uncatalog db DB_INTTD;
uncatalog db DB_INTUA;
uncatalog db DB_PRDOA;
uncatalog db DB_PRODA; 
uncatalog db DB_PRODI;
uncatalog db DB_RLSEA; 
uncatalog db DB_RLSEI;
uncatalog db DB_RLSOA;
uncatalog db DB_ST2A;
uncatalog db DB_ST2AD;
uncatalog db DB_ST2CP;
uncatalog db DB_ST2EA;
uncatalog db DB_ST2I;
uncatalog db DB_ST2LE;
uncatalog db DB_ST2OA;
uncatalog db DB_ST2SM;
uncatalog db DB_ST2TD;
uncatalog db DB_ST2UA;
uncatalog db DB_ST3A;
uncatalog db DB_ST3AD;
uncatalog db DB_ST3CP;
uncatalog db DB_ST3EA;
uncatalog db DB_ST3I;
uncatalog db DB_ST3LE;
uncatalog db DB_ST3OA;
uncatalog db DB_ST3SM;
uncatalog db DB_ST3TD;
uncatalog db DB_ST3UA;
uncatalog db DB_TRNGA; 
uncatalog db DB_TRNGI;

uncatalog system odbc data source DB_DEVLA;
uncatalog system odbc data source DB_DEVLI;
uncatalog system odbc data source DB_DEVOA;
uncatalog system odbc data source DB_DV3AD;
uncatalog system odbc data source DB_DV3CP;
uncatalog system odbc data source DB_DV3EA;
uncatalog system odbc data source DB_DV3LE;
uncatalog system odbc data source DB_DV3SM;
uncatalog system odbc data source DB_DV3TD;
uncatalog system odbc data source DB_DV3UA;
uncatalog system odbc data source DB_ECLD;
uncatalog system odbc data source DB_ECLI;
uncatalog system odbc data source DB_ECLP;
uncatalog system odbc data source DB_ECLR;
uncatalog system odbc data source DB_ECLS2;
uncatalog system odbc data source DB_ECLS3;
uncatalog system odbc data source DB_INTAD;
uncatalog system odbc data source DB_INTCP;
uncatalog system odbc data source DB_INTEA;
uncatalog system odbc data source DB_INTGA;
uncatalog system odbc data source DB_INTGI;
uncatalog system odbc data source DB_INTLE;
uncatalog system odbc data source DB_INTOA;
uncatalog system odbc data source DB_INTSM;
uncatalog system odbc data source DB_INTTD;
uncatalog system odbc data source DB_INTUA;
uncatalog system odbc data source DB_PRDOA;
uncatalog system odbc data source DB_PRODA;
uncatalog system odbc data source DB_PRODI;
uncatalog system odbc data source DB_RLSEA;
uncatalog system odbc data source DB_RLSEI;
uncatalog system odbc data source DB_RLSOA;
uncatalog system odbc data source DB_ST2A;
uncatalog system odbc data source DB_ST2AD;
uncatalog system odbc data source DB_ST2CP;
uncatalog system odbc data source DB_ST2EA;
uncatalog system odbc data source DB_ST2I;
uncatalog system odbc data source DB_ST2LE;
uncatalog system odbc data source DB_ST2OA;
uncatalog system odbc data source DB_ST2SM;
uncatalog system odbc data source DB_ST2TD;
uncatalog system odbc data source DB_ST2UA;
uncatalog system odbc data source DB_ST3A;
uncatalog system odbc data source DB_ST3AD;
uncatalog system odbc data source DB_ST3CP;
uncatalog system odbc data source DB_ST3EA;
uncatalog system odbc data source DB_ST3I;
uncatalog system odbc data source DB_ST3LE;
uncatalog system odbc data source DB_ST3OA;
uncatalog system odbc data source DB_ST3SM;
uncatalog system odbc data source DB_ST3TD;
uncatalog system odbc data source DB_ST3UA;
uncatalog system odbc data source DB_TRNGA;
uncatalog system odbc data source DB_TRNGI;

uncatalog node DB2ECL;
uncatalog node DB2ECLI;
uncatalog node DB2ECLR;
uncatalog node DB2ECLT;
uncatalog node DB2OAUT2;
uncatalog node DB2OAUTH;
uncatalog node DB2OAUTI;
uncatalog node DB2OAUTR;
uncatalog node DB2TIBD3;
uncatalog node DB2TIBI;
uncatalog node DB2TIBS2;
uncatalog node DB2TIBS3;
uncatalog node DB2WEB;
uncatalog node DB2WEBI;
uncatalog node DB2WEBR;
uncatalog node DB2WEBT;

terminate;
