SELECT * FROM ASN.IBMSNAP_SUBS_SET
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB201'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4101'
;
SELECT * FROM ASN.IBMSNAP_SUBS_SET
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB202'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4102'
;
SELECT * FROM ASN.IBMSNAP_SUBS_MEMBR
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB201'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4101'
;
SELECT * FROM ASN.IBMSNAP_SUBS_MEMBR
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB202'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4102'
;
SELECT * FROM ASN.IBMSNAP_SUBS_COLS
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB201'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4101'
;
SELECT * FROM ASN.IBMSNAP_SUBS_COLS
--UPDATE ASN.IBMSNAP_SUBS_SET
--  SET APPLY_QUAL = 'HIEDWDQUAL200',
--      SET_NAME   = 'HIEDWDSUB202'
WHERE APPLY_QUAL = 'HIEDWDQUAL4000'
  AND SET_NAME   = 'HIEDWDSUB4102'
;
