-- Step 1. Sync
CREATE TABLE DD.DD_D_MEMBER_MASTER (
  D_MMBR_SK	INTEGER	NOT NULL,
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256)	NOT NULL,
  LAST_NME	VARCHAR(50)	NOT NULL,
  TITLE	VARCHAR(20)	NOT NULL,
  MAILING_NME	VARCHAR(256)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  GEOTRIBE_CDE	VARCHAR(20)	NOT NULL,
  GEOTRIBE_SEGMENT	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  PSTL_REGION_DESC	VARCHAR(50)	NOT NULL,
  PSTL_STATE_DESC	VARCHAR(50)	NOT NULL,
  RSDNTL_REGION_DESC	VARCHAR(50)	NOT NULL,
  RSDNTL_STATE_DESC	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  STAFF_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  ETL_DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN USERSPACE1
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_D_MEMBER_MASTER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = M5P;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER M5P;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDL.D_MEMBER (
  D_MMBR_SK	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256),
  LAST_NME	VARCHAR(50),
  TITLE	VARCHAR(20),
  MAILING_NME	VARCHAR(256),
  PRFRD_CONTACT_MTHD	VARCHAR(100),
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  STAFF_FLG	CHARACTER(1 OCTETS),
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  ETL_DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN USERSPACE1
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_MEMBER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDL.D_MEMBER TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDL.D_W_MEMBER_LATEST (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256),
  LAST_NME	VARCHAR(50),
  TITLE	VARCHAR(20),
  MAILING_NME	VARCHAR(256),
  STAFF_FLG	CHARACTER(1 OCTETS),
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(10)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN USERSPACE1
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_W_MEMBER_LATEST
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_W_MEMBER_LATEST TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDWWORK.DD_D_MEMBER_WORK (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256)	NOT NULL,
  LAST_NME	VARCHAR(50)	NOT NULL,
  TITLE	VARCHAR(20)	NOT NULL,
  MAILING_NME	VARCHAR(256)	NOT NULL,
  STAFF_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  GEOTRIBE_CDE	VARCHAR(50)	NOT NULL,
  GEOTRIBE_SEGMENT	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL
  ) 
  IN USERSPACE1
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.DD_D_MEMBER_WORK
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.DD_D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDWWORK.D_MEMBER_WORK (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256),
  LAST_NME	VARCHAR(50),
  TITLE	VARCHAR(20),
  MAILING_NME	VARCHAR(256),
  STAFF_FLG	CHARACTER(1 OCTETS),
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS),
  EFF_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100),
  DOC_CHNL	VARCHAR(100),
  EMAIL_ADDR	VARCHAR(1024),
  HOME_PHONE_NUM	VARCHAR(50),
  MOBILE_PHONE_NUM	VARCHAR(50),
  WORK_PHONE_NUM	VARCHAR(50),
  OPT_IN_STATUS	VARCHAR(50),
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_SMS_STATUS	VARCHAR(50),
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50),
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDWWORK.D_MEMBER_WORK1 (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  GIVEN_NME	VARCHAR(256),
  LAST_NME	VARCHAR(50),
  TITLE	VARCHAR(20),
  MAILING_NME	VARCHAR(256),
  STAFF_FLG	CHARACTER(1 OCTETS),
  RETURN_MAIL_FLG	CHARACTER(1 OCTETS),
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1)	NOT NULL,
  PREV_CONCAT_TEMP_STR	VARCHAR(1512),
  CONCAT_TEMP_STR	VARCHAR(1512)	NOT NULL,
  DEL_FLG	VARCHAR(1)	NOT NULL,
  ETL_DEL_FLG	VARCHAR(1)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASE_DD_08K
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK1
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASBIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASBIRLSE;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASDIRLSE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASDIRLSE;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = NDD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP DB2_MIS_MON;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP EDW_ETL_DEVELOPER_RW_RLSE WITH GRANT OPTION;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_RLSE_R;

SET SCHEMA = NDD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_RLSE_SYS;

CREATE TABLE EDWWORK.D_MEMBER_WORK_CHANGES (
  MMBR_NUM	VARCHAR(20),
  EFF_DT	DATE,
  END_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100),
  DOC_CHNL	VARCHAR(100),
  EMAIL_ADDR	VARCHAR(1024),
  HOME_PHONE_NUM	VARCHAR(50),
  MOBILE_PHONE_NUM	VARCHAR(50),
  WORK_PHONE_NUM	VARCHAR(50),
  OPT_IN_STATUS	VARCHAR(50),
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_SMS_STATUS	VARCHAR(50),
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50),
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1),
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1),
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1),
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1),
  DEL_FLG	VARCHAR(1),
  ETL_DEL_FLG	VARCHAR(1),
  INSERT_BATCH_AUDIT_SK	DECIMAL(11, 0),
  UPDATE_BATCH_AUDIT_SK	DECIMAL(11, 0),
  INSERT_TS	TIMESTAMP,
  UPDATE_TS	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TABLE EDWWORK.D_MEMBER_WORK_MM (
  MMBR_NUM	VARCHAR(20),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1),
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1),
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1),
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1),
  CHANGE_FLG	VARCHAR(1),
  DEL_FLG	VARCHAR(1),
  ETL_DEL_FLG	VARCHAR(1),
  UPDATE_BATCH_AUDIT_SK	DOUBLE,
  UPDATE_TS	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TABLE EDWWORK.D_MEMBER_WORK_NEW (
  MMBR_NUM	VARCHAR(20),
  EFF_DT	DATE,
  END_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100),
  DOC_CHNL	VARCHAR(100),
  EMAIL_ADDR	VARCHAR(1024),
  HOME_PHONE_NUM	VARCHAR(50),
  MOBILE_PHONE_NUM	VARCHAR(50),
  WORK_PHONE_NUM	VARCHAR(50),
  OPT_IN_STATUS	VARCHAR(50),
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_SMS_STATUS	VARCHAR(50),
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50),
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1),
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1),
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1),
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1),
  DEL_FLG	VARCHAR(1),
  ETL_DEL_FLG	VARCHAR(1),
  INSERT_BATCH_AUDIT_SK	DECIMAL(11, 0),
  UPDATE_BATCH_AUDIT_SK	DECIMAL(11, 0),
  INSERT_TS	TIMESTAMP,
  UPDATE_TS	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK_NEW
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

-- Step 2. Restoring constraints and indexes
CREATE UNIQUE INDEX EDWWORK.XAK1DD_DD_D_MEMBER_WORK
  ON EDWWORK.DD_D_MEMBER_WORK
    ( MMBR_NUM ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX EDL.XAK1D_W_MEMBER_LATEST
  ON EDL.D_W_MEMBER_LATEST
    ( MMBR_NUM ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX EDL.XAK1D_MEMBER
  ON EDL.D_MEMBER
    ( MMBR_NUM ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX DD.XAK1DD_D_MEMBER_MASTER
  ON DD.DD_D_MEMBER_MASTER
    ( MMBR_NUM ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

ALTER TABLE DD.DD_D_MEMBER_MASTER
  ADD CONSTRAINT XPKDD_D_MEMBER_MASTER PRIMARY KEY
    (D_MMBR_SK)
    ENFORCED;

ALTER TABLE EDL.D_MEMBER
  ADD CONSTRAINT XPKD_MEMBER PRIMARY KEY
    (D_MMBR_SK)
    ENFORCED;

ALTER TABLE EDL.D_W_MEMBER_LATEST
  ADD CONSTRAINT XPK_D_W_MEMBER_LATEST PRIMARY KEY
    (MMBR_NUM)
    ENFORCED;

COMMIT;

-- Step 3. Runstats
RUNSTATS ON TABLE DD.DD_D_MEMBER_MASTER
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_MEMBER
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_W_MEMBER_LATEST
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.D_MEMBER_WORK
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.D_MEMBER_WORK_MM
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.D_MEMBER_WORK_NEW
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.D_MEMBER_WORK1
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDWWORK.DD_D_MEMBER_WORK
	ALLOW WRITE ACCESS;

SET CURRENT SCHEMA = P1K;

