CREATE SEQUENCE DEID.TABLESEQ;

SELECT 'OUTPUT SREC' || CAST(NEXT VALUE FOR DEID.TABLESEQ AS DEC(3)) || ' DSNAME HBFDSS.&DB..&TS..P&PART2..D&JDATE..SYSREC'
FROM P1K.UNLD_CNTL
UNION
SELECT 'SELECT * FROM TESTA.' CONCAT TABNAME
FROM P1K.UNLD_CNTL
WHERE P1K.UNLD_CNTL.TABNAME LIKE 'TH58%';

DROP   SEQUENCE DEID.TABLESEQ;

SELECT CAST(NEXT VALUE FOR DEID.TABLESEQ AS DEC(3))
FROM SYSIBM.SYSDUMMY1;

ALTER SEQUENCE DEID.TABLESEQ 
  RESTART WITH 1;
  