SELECT PRNT_ID,
       ACTIVE,
       PRNT_TYPE,
       PHYSICAL_LOCN,
       "DESC",
       UNC_PATH,
       PRNT_FORMAT
FROM PRODA.TP004_PRNT_DEFN
WHERE PRNT_ID = 'KSKMFD02';

UPDATE RLSEC.TP004_PRNT_DEFN
SET PRNT_FORMAT = 'PDF'
WHERE PRNT_ID = 'KS4MFD15';

INSERT INTO RLSEC.TP004_PRNT_DEFN
VALUES ('KSXMFD15',
        'Y',
        'D',
        'KS4',
        'RICOH MC250FW',
        '\\HRVPRINT1\KS4MFD15',
        'PS');

DELETE FROM RLSEC.TP004_PRNT_DEFN
WHERE PRNT_ID = 'KS4MFD15';