SELECT * FROM   PRODA.TP004_PRNT_DEFN WHERE  PRNT_ID = 'KSKMFD02';

SELECT *
FROM   PRODA.TP003_PRNT_GROUP
WHERE  PRNT_ID = 'KSKMFD02';

SELECT * FROM PRODA.TP002_PRNT_LOCN WHERE PRNT_ID = 'KSKMFD02';

SELECT DISTINCT LOCN
FROM   PRODA.TP002_PRNT_LOCN
WHERE  PRNT_ID LIKE 'BOO%';

SELECT DISTINCT LOCN
FROM   PRODA.TP002_PRNT_LOCN
WHERE  PRNT_ID LIKE 'JOO%';
