SELECT *
FROM BWDBU.AURION_EMP_CUST_JOB_CODE
WHERE PERS_NUMBER = 'HIB';

INSERT INTO BWDBU.AURION_EMP_CUST_JOB_CODE (PERS_NUMBER, JOB_CODE)
VALUES ('HIB'                                     -- PERS_NUMBER - VARCHAR(30)
             , 'HBF_PAYMENT_APPROVER'                -- JOB_CODE - VARCHAR(30)
                                     );

SELECT *
FROM BWDBU.AURION_EMP_CUST_JOB_CODE
WHERE PERS_NUMBER = 'HIB';

SELECT *
FROM BWDBU.AURION_EMP_CUST_JOB_CODE
WHERE PERS_NUMBER = 'C4G';

INSERT INTO BWDBU.AURION_EMP_CUST_JOB_CODE (PERS_NUMBER, JOB_CODE)
VALUES ('C4G'                                     -- PERS_NUMBER - VARCHAR(30)
             , 'HBF_FINANCE'                         -- JOB_CODE - VARCHAR(30)
                            );

SELECT *
FROM BWDBU.AURION_EMP_CUST_JOB_CODE
WHERE PERS_NUMBER = 'C4G';