SELECT ST.NAME, CHAR (ST.STATEMENT, 200) AS STMT_TEXT
FROM SYSIBM.SYSPACKSTMT ST
     INNER JOIN SYSIBM.SYSPACKDEP DP
        ON     ST.LOCATION = DP.DLOCATION
           AND ST.COLLID = DP.DCOLLID
           AND ST.NAME = DP.DNAME
           AND ST.CONTOKEN = DP.DCONTOKEN
WHERE     DP.BNAME = 'TW041_NEXTFIN'
      AND DP.BQUALIFIER = 'PRODA'
      AND CHAR (ST."STATEMENT", 200) LIKE '%TW041%'