UPDATE P1K.TW272_FININTEGRITY A
SET A.REPORT_TIMESTAMP =
       (CONCAT (VARCHAR_FORMAT (A.REPORT_DTE, 'YYYY-MM-DD-'),
                CHAR (A.REPORT_TIME, ISO)));

SELECT REPORT_DTE,
       REPORT_TIME,
       REPORT_TIMESTAMP,
       CONCAT (VARCHAR_FORMAT (REPORT_DTE, 'YYYY-MM-DD-'),
               CHAR (REPORT_TIME, ISO))
          AS TS_DTE_TIM
FROM P1K.TW272_FININTEGRITY;

SELECT *
FROM P1K.TW272_FININTEGRITY
WHERE     REPORT_DTE <> DATE (REPORT_TIMESTAMP)
      AND REPORT_TIME <> TIME (REPORT_TIMESTAMP);
