-- Step 1. Drop
DROP TABLE BDL."Online Eligibility Checks Product Descriptions";

DROP TABLE BDL."Online Eligibility Checks Messages";

DROP TABLE BDL."MBS Product Item Coverage";

DROP TABLE BDL."Health Insurance Product Rankings";

DROP TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS;

DROP TABLE EDL.D_OEC_MESSAGE;

DROP TABLE DD.DD_OEC_MESSAGE;

DROP TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF;

DROP TABLE DD.DD_D_HI_ASSESS_GROUP;

DROP TABLE EDL.D_HI_ITEM_PRODUCT_XREF;

DROP TABLE EDL.TRG_D_HI_ITEM;

DROP TABLE DD.DD_D_HI_ITEM;

DROP TABLE DD.DD_XREF_HI_ITEM_PRODUCT;

DROP TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT;

DROP TABLE EDL.D_HI_ASSESS_GROUP;

DROP TABLE EDL.TRG_D_PROD_COMP;

DROP TABLE DD.DD_D_PRODUCT_COMP;

COMMIT;

-- Step 2. Sync
CREATE TABLE DD.DD_D_PRODUCT_COMP (
  D_PROD_COMP_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL,
  ACTIVE_FLG	SMALLINT	NOT NULL,
  C_AUDIT_SK	INTEGER	NOT NULL,
  PROD_HIER_ID	VARCHAR(10)	NOT NULL,
  PROD_LVL_DESC	VARCHAR(50)	NOT NULL,
  BEGIN_EFF_DT	DATE	NOT NULL,
  END_EFF_DT	DATE	NOT NULL,
  LVL_NO	INTEGER	NOT NULL,
  PROD_COMP_TYP	VARCHAR(10)	NOT NULL,
  EXCESS_TYP	VARCHAR(10)	NOT NULL,
  EXCESS_TYP_DESC	VARCHAR(50)	NOT NULL,
  RATE_AMT	DECIMAL(19, 2)	NOT NULL,
  MASTER_L1_ID	VARCHAR(10)	NOT NULL,
  MASTER_L1_DESC	VARCHAR(50)	NOT NULL,
  MASTER_L1_LONG_DESC	VARCHAR(256)	NOT NULL,
  ENTITY_L2_ID	VARCHAR(10)	NOT NULL,
  ENTITY_L2_DESC	VARCHAR(50)	NOT NULL,
  ENTITY_L2_LONG_DESC	VARCHAR(256)	NOT NULL,
  BRAND_L3_ID	VARCHAR(10)	NOT NULL,
  BRAND_L3_DESC	VARCHAR(50)	NOT NULL,
  BRAND_L3_LONG_DESC	VARCHAR(256)	NOT NULL,
  PROD_CLASS_L3_ID	VARCHAR(10)	NOT NULL,
  PROD_CLASS_L3_DESC	VARCHAR(50)	NOT NULL,
  PROD_CLASS_LONG_L3_DESC	VARCHAR(256)	NOT NULL,
  PROD_ALTN_GRP_L4_ID	VARCHAR(10)	NOT NULL,
  PROD_ALTN_GRP_L4_DESC	VARCHAR(50)	NOT NULL,
  PROD_ALTN_GRP_L4_LONG_DESC	VARCHAR(256)	NOT NULL,
  PROD_GRP_L4_ID	VARCHAR(10)	NOT NULL,
  PROD_GRP_L4_DESC	VARCHAR(50)	NOT NULL,
  PROD_GRP_L4_LONG_DESC	VARCHAR(256)	NOT NULL,
  PROD_L5_ID	VARCHAR(10)	NOT NULL,
  PROD_L5_DESC	VARCHAR(50)	NOT NULL,
  PROD_L5_LONG_DESC	VARCHAR(256)	NOT NULL,
  PROD_COMP_L6_ID	VARCHAR(10)	NOT NULL,
  PROD_COMP_L6_DESC	VARCHAR(50)	NOT NULL,
  PROD_COMP_L6_LONG_DESC	VARCHAR(256)	NOT NULL,
  HOSP_TYP_ID	VARCHAR(10)	NOT NULL,
  HOSP_TYP_DESC	VARCHAR(50)	NOT NULL,
  ANCLLARY_TYP_ID	VARCHAR(10)	NOT NULL,
  ANCLLARY_TYP_DESC	VARCHAR(50)	NOT NULL,
  ACCOM_TYP_ID	VARCHAR(10)	NOT NULL,
  ACCOM_TYP_DESC	VARCHAR(50)	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS),
  OEC_PROD_COMP_L6_DESC	VARCHAR(1024)	NOT NULL	DEFAULT 'Unknown',
  OEC_PROD_COMP_DESC_EFF_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  BENEFIT_COVER_1	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  BENEFIT_COVER_2	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  PROD_SALE_CLOSE_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  PROD_WITHDRAWN_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  PROD_TYP_CDE	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  PROD_TYP_DESC	VARCHAR(50)	NOT NULL	DEFAULT 'Unknown'
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES STATIC
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_D_PRODUCT_COMP
  DATA CAPTURE NONE
  PCTFREE 10
  LOCKSIZE ROW
  APPEND OFF
  VOLATILE;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER GRM;

SET SCHEMA = M5P;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER M5P;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER MJK;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO USER SASBIDEV1;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO USER SASBIDEV1;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SASDIDEV1;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO USER SASDIDEV1;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO USER SASDIDEV1;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = P1K;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO USER V0B WITH GRANT OPTION;

GRANT CONTROL ON TABLE DD.DD_D_PRODUCT_COMP TO USER V0B;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = TWM;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV WITH GRANT OPTION;

GRANT CONTROL ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_PROD_R;

SET SCHEMA = TWM;

GRANT SELECT ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_PROD_R;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET SCHEMA = TWM;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_PRODUCT_COMP TO GROUP MIS_DB_ACCESS_PROD_SYS;

CREATE TABLE EDL.TRG_D_PROD_COMP (
  D_PROD_COMP_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL,
  C_AUDIT_SK	INTEGER	NOT NULL,
  PROD_COMP_ID	VARCHAR(10)	NOT NULL,
  BRAND_ID	VARCHAR(10)	NOT NULL,
  PROD_COMP_DESC	VARCHAR(50)	NOT NULL,
  PROD_ID	VARCHAR(10)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(10)	NOT NULL,
  EXCESS_TYP	VARCHAR(10)	NOT NULL,
  EXCESS_TYP_DESC	VARCHAR(50)	NOT NULL,
  PROD_COMP_LONG_DESC	VARCHAR(256)	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS),
  OEC_PROD_COMP_DESC	VARCHAR(1024)	NOT NULL	DEFAULT 'Unknown',
  OEC_PROD_COMP_DESC_EFF_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  BENEFIT_COVER_1	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  BENEFIT_COVER_2	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  PROD_SALE_CLOSE_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  PROD_WITHDRAWN_DT	DATE	NOT NULL	DEFAULT '9999-12-31',
  PROD_TYP_CDE	VARCHAR(20)	NOT NULL	DEFAULT 'UNK',
  PROD_TYP_DESC	VARCHAR(50)	NOT NULL	DEFAULT 'Unknown'
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES STATIC
  ORGANIZE BY ROW;

ALTER TABLE EDL.TRG_D_PROD_COMP
  DATA CAPTURE NONE
  PCTFREE 10
  LOCKSIZE ROW
  APPEND OFF
  VOLATILE;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER GRM;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER MJK;

SET SCHEMA = DB2CON;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER PYR;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO USER SASBIDEV1;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO USER SASBIDEV1;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SASDIDEV1;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO USER SASDIDEV1;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO USER SASDIDEV1;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_BI_FEDDBUSER_RLS;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO USER SVC_TBLADMIN_RLS;

SET SCHEMA = P1K;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO USER V0B WITH GRANT OPTION;

GRANT CONTROL ON TABLE EDL.TRG_D_PROD_COMP TO USER V0B;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = TWM;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP DB2_MIS_MON;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV WITH GRANT OPTION;

GRANT CONTROL ON TABLE EDL.TRG_D_PROD_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = HEL;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = V0B;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_R;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = HEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_PROD_R;

SET SCHEMA = TWM;

GRANT SELECT ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_PROD_R;

SET SCHEMA = GZD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET SCHEMA = TWM;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_PROD_COMP TO GROUP MIS_DB_ACCESS_PROD_SYS;

CREATE TABLE EDL.D_HI_ASSESS_GROUP (
  D_HI_ASSESS_GRP_SK	INTEGER	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  HI_ASSESS_GRP_DESC	VARCHAR(50)	NOT NULL,
  ASSESS_GRP_KEY_HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  ASSESS_GRP_KEY_HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_HI_ASSESS_GROUP
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = V0B;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT (
  D_PROD_COMP_SK	INTEGER	NOT NULL,
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  CONFIGURATION_DT	DATE	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  D_HI_ASSESS_GRP_SK	INTEGER	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  RANKING_NUM	SMALLINT	NOT NULL,
  RANKING_TYP	VARCHAR(20)	NOT NULL,
  RANKING_TYP_DESC	VARCHAR(256)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO USER SASDIDEV1;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE DD.DD_XREF_HI_ITEM_PRODUCT (
  D_HI_ITEM_SK	INTEGER	NOT NULL,
  HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  D_PROD_COMP_SK	INTEGER	NOT NULL,
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  CONFIGURATION_DT	DATE	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  D_HI_ASSESS_GRP_SK	INTEGER	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  HI_ASSESS_GRP_USED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  PRE_EXISTING_PERIOD	SMALLINT	NOT NULL,
  SERVICE_CDE	VARCHAR(20)	NOT NULL,
  WAIT_PERIOD	SMALLINT	NOT NULL,
  SUPPLEMENTARY_WAIT_PERIOD	SMALLINT	NOT NULL,
  RESTRICTED_FLG	VARCHAR(20)	NOT NULL,
  EXCLUDED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_XREF_HI_ITEM_PRODUCT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO USER SASDIDEV1;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE DD.DD_D_HI_ITEM (
  D_HI_ITEM_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL,
  ITEM_CDE	VARCHAR(10)	NOT NULL,
  ITEM_DESC	VARCHAR(256)	NOT NULL,
  ITEM_START_DT	DATE	NOT NULL,
  ITEM_CEASE_DT	DATE	NOT NULL,
  ACCOM_TYP_CDE	VARCHAR(10)	NOT NULL,
  ACCOM_TYP_DESC	VARCHAR(50)	NOT NULL,
  AMB_TYP	VARCHAR(10)	NOT NULL,
  AMB_DESC	VARCHAR(10)	NOT NULL,
  BEN_SEGMENT_CDE	VARCHAR(10)	NOT NULL,
  BEN_SEGMENT_DESC	VARCHAR(50)	NOT NULL,
  CRAFT_GRP_CDE	VARCHAR(10)	NOT NULL,
  CRAFT_GRP_DESC	VARCHAR(50)	NOT NULL,
  CRAFT_SUB_GRP_CDE	VARCHAR(10)	NOT NULL,
  CRAFT_SUB_GRP_DESC	VARCHAR(50)	NOT NULL,
  DRG_BROAD_GRP_CDE	VARCHAR(10)	NOT NULL,
  DRG_BROAD_GRP_DESC	VARCHAR(50)	NOT NULL,
  DRG_ADJCNT_CDE	VARCHAR(10)	NOT NULL,
  DRG_ADJCNT_DESC	VARCHAR(50)	NOT NULL,
  DRG_PARTN_CDE	VARCHAR(10)	NOT NULL,
  DRG_PARTN_SHORT_DESC	CHARACTER(1 OCTETS)	NOT NULL,
  DRG_PARTN_LONG_DESC	VARCHAR(10)	NOT NULL,
  DRG_REC_TYP_CDE	VARCHAR(10)	NOT NULL,
  DRG_REC_TYP_DESC	VARCHAR(50)	NOT NULL,
  ITEM_CAT_CDE	VARCHAR(10)	NOT NULL,
  ITEM_CAT_DESC	VARCHAR(50)	NOT NULL,
  ITEM_TYP_CDE	VARCHAR(10)	NOT NULL,
  ITEM_TYP_DESC	VARCHAR(50)	NOT NULL,
  SRVCE_TYP_CDE	VARCHAR(10)	NOT NULL,
  SRVCE_TYP_DESC	VARCHAR(50)	NOT NULL,
  DRG_ITEM_IND	VARCHAR(10)	NOT NULL,
  ADJUSTMENT_ITEM_CDE_IND	CHARACTER(1 OCTETS)	NOT NULL,
  ITEM_SUMMARY_GRP	VARCHAR(10)	NOT NULL,
  ITEM_SUMMARY_GRP_DESC	VARCHAR(50)	NOT NULL,
  MAJOR_SERVICE_GRP	VARCHAR(10)	NOT NULL,
  MAJOR_SERVICE_GRP_DESC	VARCHAR(50)	NOT NULL,
  MBS_IND	CHARACTER(1 OCTETS)	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  ASSESS_GRP_KEY_ITEM_FLG	CHARACTER(1 OCTETS)	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_D_HI_ITEM
  DATA CAPTURE NONE
  PCTFREE 10
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ITEM TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ITEM TO USER SASDIDEV1;

GRANT SELECT ON TABLE DD.DD_D_HI_ITEM TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE DD.DD_D_HI_ITEM TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE DD.DD_D_HI_ITEM TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ITEM TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE DD.DD_D_HI_ITEM TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ITEM TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE EDL.TRG_D_HI_ITEM (
  D_HI_ITEM_SK	INTEGER	NOT NULL,
  R_CODE_ACCOM_TYP_SK	INTEGER	NOT NULL,
  R_CODE_AMB_TYP_SK	INTEGER	NOT NULL,
  R_CODE_BEN_SEGMENT_SK	INTEGER	NOT NULL,
  R_CODE_CRAFT_GRP_SK	INTEGER	NOT NULL,
  R_CODE_CRAFT_SUB_GRP_SK	INTEGER	NOT NULL,
  R_CODE_DRG_BROAD_GRP_SK	INTEGER	NOT NULL,
  R_CODE_DRG_ADJCNT_SK	INTEGER	NOT NULL,
  R_CODE_DRG_PARTN_SK	INTEGER	NOT NULL,
  R_CODE_DRG_SPLIT_SK	INTEGER	NOT NULL,
  R_CODE_DRG_REC_TYP_SK	INTEGER	NOT NULL,
  R_CODE_ITEM_SUMM_GRP_SK	INTEGER	NOT NULL,
  R_CODE_MAJ_SRVCE_GRP_SK	INTEGER	NOT NULL,
  R_CODE_SRC_ITEM_CAT_SK	INTEGER	NOT NULL,
  R_CODE_SRC_ITEM_TYP_SK	INTEGER	NOT NULL,
  R_CODE_SRC_SRVCE_TYP_SK	INTEGER	NOT NULL,
  R_SOURCE_SYSTEM_SK	INTEGER	NOT NULL,
  ITEM_CDE	VARCHAR(10)	NOT NULL,
  ITEM_TYP	VARCHAR(10)	NOT NULL,
  ITEM_START_DT	DATE	NOT NULL,
  ADJUSTMENT_ITEM_CDE_IND	CHARACTER(1 OCTETS)	NOT NULL,
  DRG_ITEM_IND	VARCHAR(10)	NOT NULL,
  ITEM_DESC	VARCHAR(256)	NOT NULL,
  ITEM_CEASE_DT	DATE	NOT NULL,
  MBS_IND	CHARACTER(1 OCTETS)	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  ASSESS_GRP_KEY_ITEM_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.TRG_D_HI_ITEM
  DATA CAPTURE NONE
  PCTFREE 10
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_HI_ITEM TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_HI_ITEM TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.TRG_D_HI_ITEM TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.TRG_D_HI_ITEM TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.TRG_D_HI_ITEM TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_HI_ITEM TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.TRG_D_HI_ITEM TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.TRG_D_HI_ITEM TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE EDL.D_HI_ITEM_PRODUCT_XREF (
  HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  HI_ASSESS_GRP_USED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  RESTRICTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  PRE_EXISTING_PERIOD	SMALLINT	NOT NULL,
  SERVICE_CDE	VARCHAR(20)	NOT NULL,
  WAIT_PERIOD	SMALLINT	NOT NULL,
  SUPPLEMENTARY_WAIT_PERIOD	SMALLINT	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_HI_ITEM_PRODUCT_XREF
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE DD.DD_D_HI_ASSESS_GROUP (
  D_HI_ASSESS_GRP_SK	INTEGER	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  HI_ASSESS_GRP_DESC	VARCHAR(50)	NOT NULL,
  ASSESS_GRP_KEY_HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  ASSESS_GRP_KEY_HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_D_HI_ASSESS_GROUP
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ASSESS_GROUP TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ASSESS_GROUP TO USER SASDIDEV1;

GRANT SELECT ON TABLE DD.DD_D_HI_ASSESS_GROUP TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE DD.DD_D_HI_ASSESS_GROUP TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE DD.DD_D_HI_ASSESS_GROUP TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ASSESS_GROUP TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE DD.DD_D_HI_ASSESS_GROUP TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_HI_ASSESS_GROUP TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF (
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  RANKING_NUM	SMALLINT	NOT NULL,
  RANKING_TYP	VARCHAR(20)	NOT NULL,
  RANKING_TYP_DESC	VARCHAR(256)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE DD.DD_OEC_MESSAGE (
  D_OEC_MSG_SK	INTEGER	NOT NULL,
  OEC_MSG_NUM	INTEGER	NOT NULL,
  OEC_MSG_TYP	VARCHAR(20)	NOT NULL,
  OEC_MSG_TYP_DESC	VARCHAR(256)	NOT NULL,
  D_HI_ASSESS_GRP_SK	INTEGER	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  D_HI_ITEM_SK	INTEGER	NOT NULL,
  HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  D_PROD_COMP_SK	INTEGER	NOT NULL,
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  HI_PROVIDER_STATUS_CDE	VARCHAR(20)	NOT NULL,
  HI_PROVIDER_STATUS_DESC	VARCHAR(50)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  MSG_TXT	VARCHAR(1024)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_OEC_MESSAGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_OEC_MESSAGE TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_OEC_MESSAGE TO USER SASDIDEV1;

GRANT SELECT ON TABLE DD.DD_OEC_MESSAGE TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE DD.DD_OEC_MESSAGE TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE DD.DD_OEC_MESSAGE TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_OEC_MESSAGE TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE DD.DD_OEC_MESSAGE TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_OEC_MESSAGE TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE EDL.D_OEC_MESSAGE (
  D_OEC_MSG_SK	INTEGER	NOT NULL,
  OEC_MSG_NUM	INTEGER	NOT NULL,
  OEC_MSG_TYP	VARCHAR(20)	NOT NULL,
  OEC_MSG_TYP_DESC	VARCHAR(256)	NOT NULL,
  HI_ASSESS_GRP_CDE	VARCHAR(20)	NOT NULL,
  HI_ITEM_CDE	VARCHAR(20)	NOT NULL,
  HI_ITEM_TYP_CDE	VARCHAR(20)	NOT NULL,
  PROD_ID	VARCHAR(20)	NOT NULL,
  PROD_COMP_TYP	VARCHAR(20)	NOT NULL,
  HI_PROVIDER_STATUS_CDE	VARCHAR(20)	NOT NULL,
  HI_PROVIDER_STATUS_DESC	VARCHAR(50)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  MSG_TXT	VARCHAR(1024)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_OEC_MESSAGE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_OEC_MESSAGE TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_OEC_MESSAGE TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.D_OEC_MESSAGE TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.D_OEC_MESSAGE TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.D_OEC_MESSAGE TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_OEC_MESSAGE TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.D_OEC_MESSAGE TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_OEC_MESSAGE TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS (
  D_HI_PROVIDER_RGSTRTN_STATUS_SK	INTEGER	NOT NULL,
  HI_PROVIDER_RGSTRTN_STATUS_CDE	VARCHAR(20)	NOT NULL,
  HI_PROVIDER_RGSTRTN_STATUS_DESC	VARCHAR(50)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO USER SASBIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO GROUP DB2_MIS_MON;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO GROUP EDW_ETL_DEVELOPER_RW_DEV;

GRANT SELECT ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO GROUP MIS_DB_ACCESS_DEVL_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS TO GROUP MIS_DB_ACCESS_DEVL_SYS;

CREATE TABLE BDL."Health Insurance Product Rankings" (
  "Assess Group"	VARCHAR(20)	NOT NULL,
  "Assess Group Desc"	VARCHAR(50)	NOT NULL,
  "Product Type"	VARCHAR(20)	NOT NULL,
  "Product"	VARCHAR(20)	NOT NULL,
  "Product Desc"	VARCHAR(50)	NOT NULL,
  "Ranking"	INTEGER	NOT NULL,
  "Ranking Type"	VARCHAR(20)	NOT NULL,
  "Ranking Type Desc"	VARCHAR(256)	NOT NULL,
  "Ranking Date On"	DATE	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE BDL."Health Insurance Product Rankings"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TABLE BDL."MBS Product Item Coverage" (
  "Assess Group"	VARCHAR(20)	NOT NULL,
  "Assess Group Desc"	VARCHAR(50)	NOT NULL,
  "Item Type"	VARCHAR(20)	NOT NULL,
  "Item Code"	VARCHAR(20)	NOT NULL,
  "Item Desc"	VARCHAR(256)	NOT NULL,
  "Product"	VARCHAR(20)	NOT NULL,
  "Product Desc"	VARCHAR(50)	NOT NULL,
  "Covered Ind"	VARCHAR(50)	NOT NULL,
  "Wait Period"	INTEGER	NOT NULL,
  "Pre Exist Period"	INTEGER	NOT NULL,
  "Key Iem Flag"	CHARACTER(1 OCTETS)	NOT NULL,
  "Item Start Date"	DATE	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE BDL."MBS Product Item Coverage"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TABLE BDL."Online Eligibility Checks Messages" (
  "OEC Msg Type"	VARCHAR(20)	NOT NULL,
  "OEC Msg Desc"	VARCHAR(256)	NOT NULL,
  "OEC Msg No"	INTEGER	NOT NULL,
  "Assess Group"	VARCHAR(20)	NOT NULL,
  "Presenting Illness Desc"	VARCHAR(256)	NOT NULL,
  "Product"	VARCHAR(20)	NOT NULL,
  "Product Desc"	VARCHAR(50)	NOT NULL,
  "Item Type"	VARCHAR(20)	NOT NULL,
  "Item Code"	VARCHAR(20)	NOT NULL,
  "Item Short Desc"	VARCHAR(50)	NOT NULL,
  "Provider Status"	VARCHAR(50)	NOT NULL,
  "OEC Msg Date On"	DATE	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE BDL."Online Eligibility Checks Messages"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TABLE BDL."Online Eligibility Checks Product Descriptions" (
  "Product"	VARCHAR(20)	NOT NULL,
  "Product Desc"	VARCHAR(50)	NOT NULL,
  "OEC Product Desc"	VARCHAR(1024)	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE BDL."Online Eligibility Checks Product Descriptions"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

-- Step 3. Restoring constraints and indexes
CREATE UNIQUE INDEX EDL.XAK1TRG_D_PROD_COMP
  ON EDL.TRG_D_PROD_COMP
    ( PROD_COMP_ID ASC, BRAND_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX EDL.XAK1D_HI_PROVIDER_RGSTRTN_STATUS
  ON EDL.D_HI_PROVIDER_RGSTRTN_STATUS
    ( HI_PROVIDER_RGSTRTN_STATUS_CDE ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX EDL.XPKTRG_D_PROD_COMP
  ON EDL.TRG_D_PROD_COMP
    ( D_PROD_COMP_SK ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX DD.XAK1DD_OEC_MESSAGE
  ON DD.DD_OEC_MESSAGE
    ( OEC_MSG_NUM ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX EDL.XAK1D_OEC_MESSAGE
  ON EDL.D_OEC_MESSAGE
    ( OEC_MSG_NUM ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX DD.XAK1DD_D_HI_ASSESS_GROUP
  ON DD.DD_D_HI_ASSESS_GROUP
    ( HI_ASSESS_GRP_CDE ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX DD.XAK1PRODUCT_COMP_DIM
  ON DD.DD_D_PRODUCT_COMP
    ( PROD_HIER_ID ASC, PROD_LVL_DESC ASC, BEGIN_EFF_DT ASC, BRAND_L3_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX DD.XAK1DD_D_HI_ITEM
  ON DD.DD_D_HI_ITEM
    ( ITEM_CDE ASC, ITEM_TYP_CDE ASC, ITEM_START_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX EDL.XAK1TRG_D_HI_ITEM
  ON EDL.TRG_D_HI_ITEM
    ( ITEM_CDE ASC, ITEM_TYP ASC, ITEM_START_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

CREATE UNIQUE INDEX EDL.XAK1D_HI_ASSESS_GROUP
  ON EDL.D_HI_ASSESS_GROUP
    ( HI_ASSESS_GRP_CDE ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

ALTER TABLE DD.DD_D_HI_ASSESS_GROUP
  ADD CONSTRAINT XPKDD_D_HI_ASSESS_GROUP PRIMARY KEY
    (D_HI_ASSESS_GRP_SK)
    ENFORCED;

ALTER TABLE DD.DD_D_HI_ITEM
  ADD CONSTRAINT XPKDD_D_HI_ITEM PRIMARY KEY
    (D_HI_ITEM_SK)
    ENFORCED;

ALTER TABLE DD.DD_D_PRODUCT_COMP
  ADD PRIMARY KEY
    (D_PROD_COMP_SK)
    ENFORCED;

ALTER TABLE DD.DD_OEC_MESSAGE
  ADD CONSTRAINT XPKDD_OEC_MESSAGE PRIMARY KEY
    (D_OEC_MSG_SK)
    ENFORCED;

ALTER TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT
  ADD CONSTRAINT XPKDD_XREF_HI_ASSESS_GROUP_PRODUCT PRIMARY KEY
    (D_PROD_COMP_SK, CONFIGURATION_DT, D_HI_ASSESS_GRP_SK)
    ENFORCED;

ALTER TABLE DD.DD_XREF_HI_ITEM_PRODUCT
  ADD CONSTRAINT XPKDD_D_HI_ITEM_PRODUCT_XREF PRIMARY KEY
    (D_PROD_COMP_SK, CONFIGURATION_DT, D_HI_ITEM_SK)
    ENFORCED;

ALTER TABLE EDL.D_HI_ASSESS_GROUP
  ADD CONSTRAINT XPKD_HI_ASSESS_GROUP PRIMARY KEY
    (D_HI_ASSESS_GRP_SK)
    ENFORCED;

ALTER TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF
  ADD CONSTRAINT XPKD_HI_ASSESS_GROUP_PRODUCT_XREF PRIMARY KEY
    (PROD_ID, EFF_DT, HI_ASSESS_GRP_CDE)
    ENFORCED;

ALTER TABLE EDL.D_HI_ITEM_PRODUCT_XREF
  ADD CONSTRAINT XPKD_HI_ITEM_PRODUCT_XREF PRIMARY KEY
    (HI_ITEM_CDE, HI_ITEM_TYP_CDE, PROD_ID, EFF_DT)
    ENFORCED;

ALTER TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS
  ADD CONSTRAINT XPKD_HI_PROVIDER_RGSTRTN_STATUS PRIMARY KEY
    (D_HI_PROVIDER_RGSTRTN_STATUS_SK)
    ENFORCED;

ALTER TABLE EDL.D_OEC_MESSAGE
  ADD CONSTRAINT XPKD_OEC_MESSAGE PRIMARY KEY
    (D_OEC_MSG_SK)
    ENFORCED;

ALTER TABLE EDL.TRG_D_HI_ITEM
  ADD CONSTRAINT XPKTRG_D_HI_ITEM PRIMARY KEY
    (D_HI_ITEM_SK)
    ENFORCED;

ALTER TABLE EDL.TRG_D_PROD_COMP
  ADD PRIMARY KEY
    (D_PROD_COMP_SK)
    ENFORCED;

COMMIT;

-- Step 4. Runstats
RUNSTATS ON TABLE BDL."Health Insurance Product Rankings"
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL."MBS Product Item Coverage"
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL."Online Eligibility Checks Messages"
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL."Online Eligibility Checks Product Descriptions"
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_D_HI_ASSESS_GROUP
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_D_HI_ITEM
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_D_PRODUCT_COMP
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_OEC_MESSAGE
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_XREF_HI_ASSESS_GROUP_PRODUCT
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE DD.DD_XREF_HI_ITEM_PRODUCT
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_HI_ASSESS_GROUP
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_HI_ASSESS_GROUP_PRODUCT_XREF
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_HI_ITEM_PRODUCT_XREF
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_HI_PROVIDER_RGSTRTN_STATUS
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.D_OEC_MESSAGE
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.TRG_D_HI_ITEM
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE EDL.TRG_D_PROD_COMP
	ALLOW WRITE ACCESS;

SET CURRENT SCHEMA = P1K;

