ALTER TABLE HI.TH581_MAGM_AGMT
   ADD COLUMN FILE_LOAD_DTE DATE NOT NULL WITH DEFAULT;

LOCK TABLE HI.TH581_MAGM_AGMT IN EXCLUSIVE MODE;

UPDATE HI.TH581_MAGM_AGMT T1
SET T1.FILE_LOAD_DTE =
       (SELECT T2.STATUS_DTE
        FROM HI.TH581_MAGM_AGMT T2
        WHERE     T1.AGREEMENT_NO = T2.AGREEMENT_NO
              AND T1.AGREEMENT_VERS_NO = T2.AGREEMENT_VERS_NO);

COMMIT;

LOCK TABLE HI.TH581_MAGM_AGMT IN EXCLUSIVE MODE;

UPDATE HI.TH581_MAGM_AGMT A
SET A.STATUS_CDE = 'PENDING',
    A.LST_UPD_USERID = 'FIX',
    A.LST_UPD_TERMINAL = 'BTCH',
    A.LST_UPD_TIMESTAMP = CURRENT TIMESTAMP
WHERE     A.PUBLIC_SALARY_IND = 'Y'
      AND A.STATUS_CDE <> 'PENDING'
      AND A.AGREEMENT_VERS_NO = (SELECT MAX (B.AGREEMENT_VERS_NO)
                                 FROM HI.TH581_MAGM_AGMT B
                                 WHERE B.AGREEMENT_NO = A.AGREEMENT_NO)
      AND NOT EXISTS
             (SELECT 1
              FROM HI.TW380_LINKPROVIDER C
              WHERE     C.PROVIDER_DOH = A.PROVIDER_DOH
                    AND C.DTE_OFF > CURRENT DATE
                    AND C.AGREEMENT_TYPE = 'GRP9');

COMMIT;

REORG TABLE HI.TH581_MAGM_AGMT;

RUNSTATS ON TABLE HI.TH581_MAGM_AGMT ON ALL COLUMNS;