-- Step 1. Drop
DROP TABLE SEMANTIC.SEM_HI_QUOTES_SALE;
-- Step 2. Sync
ALTER TABLE CGUGI.SEM_CGU_GI_QUOTES
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

SET CURRENT SCHEMA = SEMANTIC;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,PYR;

-- Warning: View create script may contain dropped or renamed columns and may require user modification
DROP VIEW CGUGI.SEM_CGU_GI_QUOTES_V;
CREATE OR REPLACE VIEW CGUGI.SEM_CGU_GI_QUOTES_V
AS
SELECT "Processed Date",  "Employee UserId",  "Group",  "Division",  "Department",  "Sub Department",  "Branch Area",  "Team ID",  "Team Name",  "Entity",  "Channel",  "State",  "Product Class",  "Product Group",  "Quote Type",  SUM("GI Quote Count") "GI Quote Count",  SUM("GI Quote Premium") "GI Quote Premium"     
  FROM (     
  SELECT QUOTES.ORIGINAL_REPORTING_DT AS "Processed Date",  QUOTES.HBF_USER_ID            AS "Employee UserId",  COALESCE(MORG.GROUP_L2_DESC,'Unknown') AS "Group",  COALESCE(MORG.DIVISION_L3_DESC,'Unknown') AS "Division",  COALESCE(MORG.DEPT_L4_DESC,'Unknown') AS "Department",  COALESCE(MORG.SUB_DEPT_L5_DESC,'Unknown') AS "Sub Department",  COALESCE(MORG.BRANCH_L6_DESC,'Unknown') AS "Branch Area",  COALESCE(MORG.TEAM_L7_ID,'UNK') AS "Team ID",  COALESCE(MORG.TEAM_L7_DESC,'Unknown') AS "Team Name",  QUOTES.ENTITY AS "Entity",  QUOTES.CHANNEL AS "Channel",  QUOTES.STATE AS "State",  DDPCOMP.PROD_CLASS_L3_DESC AS "Product Class",  RISK_TYPE AS "Product Group",  'ACQUISITION' AS "Quote Type",  QUOTE_CNT AS "GI Quote Count",  QUOTE_AMT AS "GI Quote Premium"     
  FROM CGUGI.SEM_CGU_GI_QUOTES QUOTES LEFT OUTER JOIN WAREHOUSE.NICKNAME_DD_D_MGMT_ORG MORG ON MORG.MGMT_ORG_ID  = (CASE WHEN QUOTES.CHANNEL='Internet' THEN '1136' ELSE COALESCE(QUOTES.HBF_TEAM_ID,'UNK')     
  END) AND MORG.MGMT_LVL_NO = 7 AND MORG.GROUP_L2_ID = '1002' INNER JOIN WAREHOUSE.NICKNAME_DD_D_PRODUCT_COMP DDPCOMP ON QUOTES.PROD_CLASS_L3_ID = DDPCOMP.PROD_CLASS_L3_ID AND DDPCOMP.LVL_NO = 3     
  WHERE YEAR(QUOTES.ORIGINAL_REPORTING_DT) >= YEAR(CURRENT DATE) -5 ) SUBQ GROUP BY "Processed Date",  "Group",  "Division",  "Department",  "Sub Department",  "Branch Area",  "Team ID",  "Team Name",  "Employee UserId",  "Entity",  "Channel",  "State",  "Product Class",  "Product Group",  "Quote Type";

SET SCHEMA = GZD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER GRM;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASBIDEV1;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASBIPROD;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASBIRLSE;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASDIDEV1;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASDIPROD;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SASDIRLSE;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP DB2_MIS_MON;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP MIS_ROLE_VIABILITY;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_PROD_BI;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_PROD_BUS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_PROD_R;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_QUOTES_V TO GROUP RDS_DB_ACCESS_RLSE_R;

ALTER TABLE CGUGI.SEM_CGU_GI_NET_SALE
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

SET CURRENT SCHEMA = SEMANTIC;

-- Warning: View create script may contain dropped or renamed columns and may require user modification
DROP VIEW CGUGI.SEM_CGU_GI_SALE_V;
CREATE OR REPLACE VIEW CGUGI.SEM_CGU_GI_SALE_V
AS
SELECT                   SALES.ORIGINAL_REPORTING_DT            AS "Processed Date",                   SALES.HBF_USER_ID      AS "Employee UserId",                   COALESCE(MORG.GROUP_L2_DESC,'Unknown')           AS "Group",                   COALESCE(MORG.DIVISION_L3_DESC,'Unknown')        AS "Division",                   COALESCE(MORG.DEPT_L4_DESC,'Unknown')            AS "Department",                   COALESCE(MORG.SUB_DEPT_L5_DESC,'Unknown')        AS "Sub Department",                   COALESCE(MORG.BRANCH_L6_DESC,'Unknown')          AS "Branch Area",                   COALESCE(MORG.TEAM_L7_ID,'UNK')                  AS "Team ID",                   COALESCE(MORG.TEAM_L7_DESC,'Unknown')            AS "Team Name",                   SALES.ENTITY                                     AS "Entity",                   SALES.CHANNEL                                    AS "Channel",                   SALES.STATE                                      AS "State",                   DDPCOMP.PROD_CLASS_L3_DESC                       AS "Product Class",                   SALES.RISK_TYPE                                  AS "Product Group",                   'ACQUISITION'                                    AS "Sale Type",                   SUM(SALE_CNT)                                    AS "GI Financial Sales",                   SUM(SALE_AMT)                                    AS "GI Financial GWP"     
  FROM     CGUGI.SEM_CGU_GI_NET_SALE SALES LEFT OUTER JOIN WAREHOUSE.NICKNAME_DD_D_MGMT_ORG MORG ON MORG.MGMT_ORG_ID = (CASE WHEN SALES.CHANNEL='Internet' THEN '1136' ELSE COALESCE(SALES.HBF_TEAM_ID,'UNK')     
  END) AND MORG.MGMT_LVL_NO = 7 AND MORG.GROUP_L2_ID = '1002'     INNER JOIN WAREHOUSE.NICKNAME_DD_D_PRODUCT_COMP DDPCOMP ON SALES.PROD_CLASS_L3_ID = DDPCOMP.PROD_CLASS_L3_ID AND DDPCOMP.LVL_NO = 3     
  WHERE     YEAR(SALES.ORIGINAL_REPORTING_DT) >= YEAR(CURRENT DATE) -5     GROUP BY     SALES.ORIGINAL_REPORTING_DT,     SALES.HBF_USER_ID,     COALESCE(MORG.GROUP_L2_DESC,'Unknown'),     COALESCE(MORG.DIVISION_L3_DESC,'Unknown'),     COALESCE(MORG.DEPT_L4_DESC,'Unknown'),     COALESCE(MORG.SUB_DEPT_L5_DESC,'Unknown'),     COALESCE(MORG.BRANCH_L6_DESC,'Unknown'),     COALESCE(MORG.TEAM_L7_ID,'UNK'),     COALESCE(MORG.TEAM_L7_DESC,'Unknown'),     SALES.ENTITY,     SALES.CHANNEL,     SALES.STATE,    DDPCOMP.PROD_CLASS_L3_DESC,     SALES.RISK_TYPE,     'ACQUISITION';

SET SCHEMA = GZD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER GRM;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASBIDEV1;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASBIPROD;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASBIRLSE;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASDIDEV1;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASDIPROD;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASDIRLSE;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP DB2_MIS_MON;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP MIS_ROLE_VIABILITY;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_PROD_BI;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_PROD_BUS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_PROD_R;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_R;

ALTER TABLE SEMANTIC.SEM_CGUGI_QUOTES_SALE
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

ALTER TABLE SEMANTIC.SEM_HI_GI_QUOTES_SALE
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

ALTER TABLE SEMANTIC.SEM_HI_GI_QUOTES_SALE_TRAFFIC
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

ALTER TABLE SEMANTIC.SEM_HI_GI_TQS_ACTUALS_TARGETS
  ADD COLUMN STATE	VARCHAR(10)	NOT NULL	DEFAULT ;

CREATE TABLE SEMANTIC.SEM_HI_QUOTES_SALE (
  "Processed Date"	DATE	NOT NULL,
  "Group"	VARCHAR(50)	NOT NULL,
  "Division"	VARCHAR(50)	NOT NULL,
  "Department"	VARCHAR(50)	NOT NULL,
  "Sub Department"	VARCHAR(50)	NOT NULL,
  "Branch Area"	VARCHAR(50)	NOT NULL,
  "Team ID"	VARCHAR(10)	NOT NULL,
  "Team Name"	VARCHAR(50)	NOT NULL,
  "Employee UserId"	VARCHAR(20)	NOT NULL	DEFAULT ,
  "Employee First Name"	VARCHAR(50)	NOT NULL	DEFAULT ,
  "Employee Last Name"	VARCHAR(50)	NOT NULL	DEFAULT ,
  "Entity"	VARCHAR(20)	NOT NULL,
  "Channel"	VARCHAR(20)	NOT NULL,
  "State"	VARCHAR(10)	NOT NULL	DEFAULT ,
  "Product Class"	VARCHAR(50)	NOT NULL,
  "Product Group"	VARCHAR(50)	NOT NULL,
  "Sale Type"	VARCHAR(50)	NOT NULL,
  "HI Quotes"	INTEGER	NOT NULL,
  "HI Pending Sales"	INTEGER	NOT NULL,
  "HI Pending Sale Amount"	DECIMAL(14, 2)	NOT NULL	DEFAULT ,
  "HI Financial Sales"	INTEGER	NOT NULL,
  "HI Financial Sale Amount"	DECIMAL(14, 2)	NOT NULL	DEFAULT ,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASE_SEM_16K
  INDEX IN TBS_IDX_SEM_16K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE SEMANTIC.SEM_HI_QUOTES_SALE
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER GRM;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASBIDEV1;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASBIPROD;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASDIDEV1 WITH GRANT OPTION;

GRANT CONTROL ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASDIPROD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SASDIRLSE;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP MIS_ROLE_VIABILITY;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_PROD_BI;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_PROD_BUS;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_PROD_R;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE TO GROUP RDS_DB_ACCESS_RLSE_R;

COMMIT;

-- Step 3. Runstats
RUNSTATS ON TABLE SEMANTIC.SEM_HI_QUOTES_SALE
	ALLOW WRITE ACCESS;

SET CURRENT SCHEMA = P1K;

