ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "myHBF_Terms_Accepted_Flag" CHARACTER (1);

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "myHBF_Terms_Accepted_Date" DATE;

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "myHBF_First_Login_Date" DATE;

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "myHBF_Last_Login_Date" DATE;

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "myHBF_Active_Flag" CHARACTER (1);

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "Document_Channel" VARCHAR (100);

ALTER TABLE ELOQUA.ELOQUA_CONTACT
   ADD COLUMN "Test_Member_Flag" CHARACTER (1);

COMMIT;

REORG TABLE "ELOQUA"."ELOQUA_CONTACT";