-- Step 1. Sync
CREATE TABLE BDL.CLAIMDOCUMENT (
  ID	INTEGER	NOT NULL,
  CLAIMID	INTEGER	NOT NULL,
  DOCUMENTID	INTEGER	NOT NULL,
  CREATEDDATE	TIMESTAMP	NOT NULL,
  MODIFIEDDATE	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.CLAIMDOCUMENT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = PYR;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIMDOCUMENT TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIMDOCUMENT TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIMDOCUMENT TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIMDOCUMENT TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.CLAIMDOCUMENT TO GROUP MIS_ROLE_VIABILITY;

CREATE TABLE BDL.CLAIM (
  ID	INTEGER	NOT NULL,
  MEMBERID	INTEGER	NOT NULL,
  POLICYNUMBER	VARCHAR(1000)	NOT NULL,
  ISAMBULANCECLAIM	CHARACTER(1 OCTETS)	NOT NULL,
  MEMBERHASCAP	CHARACTER(1 OCTETS)	NOT NULL,
  MEMBERHASPCC	CHARACTER(1 OCTETS)	NOT NULL,
  ISACCIDENTCLAIM	CHARACTER(1 OCTETS)	NOT NULL,
  MEMBERWOULDCLAIMCOMPENSATION	INTEGER	NOT NULL,
  USEGAPSAVER	CHARACTER(1 OCTETS)	NOT NULL,
  STATUS	INTEGER	NOT NULL,
  CREATEDDATE	TIMESTAMP	NOT NULL,
  MODIFIEDDATE	TIMESTAMP	NOT NULL,
  PENSIONNUMBER	VARCHAR(1000),
  MEMBERHASVA	CHARACTER(1 OCTETS)	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.CLAIM
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIM TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIM TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIM TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.CLAIM TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.CLAIM TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.CLAIM TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.CLAIM TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.CLAIM TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.CLAIM TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.CLAIM TO GROUP MIS_ROLE_VIABILITY;

CREATE TABLE BDL.DOCUMENT (
  ID	INTEGER	NOT NULL,
  CREATEDDATE	TIMESTAMP	NOT NULL,
  MODIFIEDDATE	TIMESTAMP	NOT NULL,
  FILENAME	VARCHAR(1000)	NOT NULL,
  FILETYPE	INTEGER	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.DOCUMENT
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.DOCUMENT TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.DOCUMENT TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.DOCUMENT TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.DOCUMENT TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.DOCUMENT TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.DOCUMENT TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.DOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.DOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.DOCUMENT TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.DOCUMENT TO GROUP MIS_ROLE_VIABILITY;

CREATE TABLE BDL.MEMBERREGISTRATION (
  ID	INTEGER	NOT NULL,
  MEMBERID	INTEGER	NOT NULL,
  REQUESTGUID	CHARACTER(36 OCTETS)	NOT NULL,
  ISCOMPLETED	CHARACTER(1 OCTETS)	NOT NULL,
  EXPIRYDATE	TIMESTAMP	NOT NULL,
  EMAILADDRESS	VARCHAR(1000),
  CREATEDDATE	TIMESTAMP	NOT NULL,
  MODIFIEDDATE	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.MEMBERREGISTRATION
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBERREGISTRATION TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBERREGISTRATION TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBERREGISTRATION TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBERREGISTRATION TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.MEMBERREGISTRATION TO GROUP MIS_ROLE_VIABILITY;

CREATE TABLE BDL.MEMBER (
  ID	INTEGER	NOT NULL,
  MEMBERNUMBER	VARCHAR(8)	NOT NULL,
  LASTTERMSANDCONDITIONSVERSION	INTEGER,
  CREATEDDATE	TIMESTAMP	NOT NULL,
  MODIFIEDDATE	TIMESTAMP	NOT NULL,
  SHOWWELCOMEPANEL	CHARACTER(1 OCTETS)	NOT NULL,
  LASTLOGIN	TIMESTAMP,
  SHOWIMPORTANTDOCUMENTBANNER	CHARACTER(1 OCTETS)	NOT NULL
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.MEMBER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBER TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBER TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBER TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.MEMBER TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.MEMBER TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.MEMBER TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.MEMBER TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.MEMBER TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.MEMBER TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.MEMBER TO GROUP MIS_ROLE_VIABILITY;

CREATE TABLE BDL.LOG (
  ID	INTEGER	NOT NULL,
  LOGGED	TIMESTAMP	NOT NULL,
  LEVEL	VARCHAR(50)	NOT NULL,
  MESSAGE	VARCHAR(15000)	NOT NULL,
  SERVER	VARCHAR(50)	NOT NULL,
  LOGGER	VARCHAR(250),
  CALLSITE	VARCHAR(1000),
  EXCEPTION	VARCHAR(15000),
  MEMBERNO	VARCHAR(255)
  ) 
  IN TBS_BASEC_BDL_32K
  INDEX IN TBS_IDXC_BDL_32K
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE BDL.LOG
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.LOG TO USER SASBIDEV1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE BDL.LOG TO USER SASBIRLSE;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.LOG TO USER SASDIDEV1;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE BDL.LOG TO USER SASDIRLSE;

GRANT SELECT ON TABLE BDL.LOG TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE BDL.LOG TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE BDL.LOG TO GROUP MIS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON TABLE BDL.LOG TO GROUP MIS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON TABLE BDL.LOG TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON TABLE BDL.LOG TO GROUP MIS_ROLE_VIABILITY;

-- Step 2. Restoring constraints and indexes
--This is system required index
CREATE UNIQUE INDEX BDL.X_CLAIMDOCUMENT01
  ON BDL.CLAIMDOCUMENT
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX BDL.X_CLAIM01
  ON BDL.CLAIM
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX BDL.X_DOCUMENT01
  ON BDL.DOCUMENT
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX BDL.X_MEMBERREGISTRATION01
  ON BDL.MEMBERREGISTRATION
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX BDL.X_MEMBER01
  ON BDL.MEMBER
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

--This is system required index
CREATE UNIQUE INDEX BDL.X_LOG01
  ON BDL.LOG
    ( ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

ALTER TABLE BDL.CLAIM
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

ALTER TABLE BDL.CLAIMDOCUMENT
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

ALTER TABLE BDL.DOCUMENT
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

ALTER TABLE BDL.LOG
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

ALTER TABLE BDL.MEMBER
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

ALTER TABLE BDL.MEMBERREGISTRATION
  ADD PRIMARY KEY
    (ID)
    ENFORCED;

COMMIT;

-- Step 3. Runstats
RUNSTATS ON TABLE BDL.CLAIM
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL.CLAIMDOCUMENT
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL.DOCUMENT
	AND INDEXES ALL
	ALLOW READ ACCESS;


RUNSTATS ON TABLE "BDL"."DOCUMENT" ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS
SET PROFILE ONLY;

RUNSTATS ON TABLE BDL.LOG
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL.MEMBER
	ALLOW WRITE ACCESS;

RUNSTATS ON TABLE BDL.MEMBERREGISTRATION
	ALLOW WRITE ACCESS;

SET CURRENT SCHEMA = P1K;

