ALTER TABLE DD.DD_D_MEMBER_MASTER
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE DD.DD_D_MEMBER_MASTER
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE DD.DD_D_MEMBER_MASTER
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE DD.DD_D_MEMBER_MASTER
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE DD.DD_D_MEMBER_MASTER;

ALTER TABLE EDL.D_MEMBER
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDL.D_MEMBER
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDL.D_MEMBER
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDL.D_MEMBER
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDL.D_MEMBER;

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_MEMBER_WORK_MM;

ALTER TABLE EDWWORK.D_MEMBER_WORK
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_MEMBER_WORK;

ALTER TABLE EDWWORK.D_MEMBER_WORK1
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK1
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_MEMBER_WORK1
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_MEMBER_WORK1
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_MEMBER_WORK1;

ALTER TABLE EDWWORK.DD_D_MEMBER_WORK
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.DD_D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.DD_D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.DD_D_MEMBER_WORK
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.DD_D_MEMBER_WORK;

ALTER TABLE EDWWORK.D_W_MEMBER_LATEST_WORK
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_W_MEMBER_LATEST_WORK
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDWWORK.D_W_MEMBER_LATEST_WORK
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_W_MEMBER_LATEST_WORK
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_W_MEMBER_LATEST_WORK;

ALTER TABLE EDL.D_W_MEMBER_LATEST
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDL.D_W_MEMBER_LATEST
   ADD COLUMN LATEST_VULNERABLE_FLG CHARACTER (1) NOT NULL DEFAULT 'N';

ALTER TABLE EDL.D_W_MEMBER_LATEST
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDL.D_W_MEMBER_LATEST
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDL.D_W_MEMBER_LATEST;

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG VARCHAR (1);

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
   ADD COLUMN LATEST_VULNERABLE_FLG VARCHAR (1);

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_MEMBER_WORK_CHANGES;

ALTER TABLE EDWWORK.D_MEMBER_WORK_NEW
   ADD COLUMN LATEST_MARKET_RESEARCH_FLG VARCHAR (1);

ALTER TABLE EDWWORK.D_MEMBER_WORK_NEW
   ADD COLUMN LATEST_VULNERABLE_FLG VARCHAR (1);

ALTER TABLE EDWWORK.D_MEMBER_WORK_NEW
   ADD COLUMN LATEST_VULNERABLE_START_DT DATE;

ALTER TABLE EDWWORK.D_MEMBER_WORK_NEW
   ADD COLUMN LATEST_VULNERABLE_EXPIRY_DT DATE;

REORG TABLE EDWWORK.D_MEMBER_WORK_NEW;