--***********************************
-- RUN THESE COMMANDS ON THE PRIMARY 
--***********************************
 
USE [master];
 
EXECUTE master.dbo.xp_create_subdir 'G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation'
 
--Database: DefaultPowerPivotSer Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3];
BACKUP DATABASE [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: FIMSynchronizationSe Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [FIMSynchronizationService];
BACKUP DATABASE [FIMSynchronizationService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\FIMSynchronizationService_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'FIMSynchronizationService_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [FIMSynchronizationService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\FIMSynchronizationService_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'FIMSynchronizationService_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: NW2016DB_Config Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [NW2016DB_Config];
BACKUP DATABASE [NW2016DB_Config] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Config_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Config_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [NW2016DB_Config] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Config_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Config_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: NW2016DB_Content Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [NW2016DB_Content];
BACKUP DATABASE [NW2016DB_Content] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Content_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Content_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [NW2016DB_Content] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Content_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Content_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: NW2016DB_Forms Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [NW2016DB_Forms];
BACKUP DATABASE [NW2016DB_Forms] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Forms_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Forms_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [NW2016DB_Forms] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Forms_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Forms_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: NW2016DB_Temp Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [NW2016DB_Temp];
BACKUP DATABASE [NW2016DB_Temp] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Temp_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Temp_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [NW2016DB_Temp] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Temp_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'NW2016DB_Temp_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_App_Manageme Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_App_Management];
BACKUP DATABASE [SP16PRD_App_Management] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_App_Management_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_App_Management_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_App_Management] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_App_Management_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_App_Management_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Config Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Config];
BACKUP DATABASE [SP16PRD_Config] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Config_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Config_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Config] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Config_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Config_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Appl Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Applications];
BACKUP DATABASE [SP16PRD_Content_Applications] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Applications_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Applications_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Applications] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Applications_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Applications_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Busi Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_BusinessRules];
BACKUP DATABASE [SP16PRD_Content_BusinessRules] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_BusinessRules_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_BusinessRules_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_BusinessRules] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_BusinessRules_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_BusinessRules_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Cent Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_CentralAdmin];
BACKUP DATABASE [SP16PRD_Content_CentralAdmin] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CentralAdmin_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CentralAdmin_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_CentralAdmin] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CentralAdmin_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CentralAdmin_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community];
BACKUP DATABASE [SP16PRD_Content_Community] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_00];
BACKUP DATABASE [SP16PRD_Content_Community_00] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_00_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_00_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_00] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_00_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_00_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_01];
BACKUP DATABASE [SP16PRD_Content_Community_01] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_01_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_01_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_01] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_01_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_01_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_02];
BACKUP DATABASE [SP16PRD_Content_Community_02] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_02_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_02_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_02] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_02_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_02_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_03];
BACKUP DATABASE [SP16PRD_Content_Community_03] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_03_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_03_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_03] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_03_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_03_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_04];
BACKUP DATABASE [SP16PRD_Content_Community_04] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_04_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_04_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_04] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_04_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_04_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Comm Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Community_05];
BACKUP DATABASE [SP16PRD_Content_Community_05] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_05_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_05_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Community_05] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_05_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Community_05_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Corp Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_CorpLibrary];
BACKUP DATABASE [SP16PRD_Content_CorpLibrary] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpLibrary_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CorpLibrary_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_CorpLibrary] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpLibrary_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CorpLibrary_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Corp Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_CorpMediaLibrary];
BACKUP DATABASE [SP16PRD_Content_CorpMediaLibrary] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_CorpMediaLibrary] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Digi Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_DigitalWorkplace];
BACKUP DATABASE [SP16PRD_Content_DigitalWorkplace] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_DigitalWorkplace_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_DigitalWorkplace_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_DigitalWorkplace] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_DigitalWorkplace_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_DigitalWorkplace_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_MyPu Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_MyPulse];
BACKUP DATABASE [SP16PRD_Content_MyPulse] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_MyPulse_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_MyPulse_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_MyPulse] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_MyPulse_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_MyPulse_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Proj Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Projects];
BACKUP DATABASE [SP16PRD_Content_Projects] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Projects_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Projects_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Projects] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Projects_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Projects_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Content_Sear Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Content_Search];
BACKUP DATABASE [SP16PRD_Content_Search] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Search_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Search_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Content_Search] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Search_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Content_Search_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_MetaData Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_MetaData];
BACKUP DATABASE [SP16PRD_MetaData] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_MetaData_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_MetaData_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_MetaData] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_MetaData_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_MetaData_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Profile Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Profile];
BACKUP DATABASE [SP16PRD_Profile] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Profile_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Profile_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Profile] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Profile_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Profile_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Search Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Search];
BACKUP DATABASE [SP16PRD_Search] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Search] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Search_Analy Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Search_AnalyticsReportingStore];
BACKUP DATABASE [SP16PRD_Search_AnalyticsReportingStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Search_AnalyticsReportingStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Search_Crawl Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Search_CrawlStore];
BACKUP DATABASE [SP16PRD_Search_CrawlStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_CrawlStore_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_CrawlStore_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Search_CrawlStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_CrawlStore_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_CrawlStore_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Search_Links Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Search_LinksStore];
BACKUP DATABASE [SP16PRD_Search_LinksStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_LinksStore_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_LinksStore_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Search_LinksStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_LinksStore_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Search_LinksStore_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_SecureStore Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_SecureStore];
BACKUP DATABASE [SP16PRD_SecureStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SecureStore_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_SecureStore_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_SecureStore] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SecureStore_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_SecureStore_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Social Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Social];
BACKUP DATABASE [SP16PRD_Social] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Social_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Social_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Social] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Social_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Social_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_StateService Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_StateService];
BACKUP DATABASE [SP16PRD_StateService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_StateService_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_StateService_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_StateService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_StateService_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_StateService_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Subscription Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_SubscriptionSettings];
BACKUP DATABASE [SP16PRD_SubscriptionSettings] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SubscriptionSettings_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_SubscriptionSettings_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_SubscriptionSettings] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SubscriptionSettings_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_SubscriptionSettings_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_Sync Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_Sync];
BACKUP DATABASE [SP16PRD_Sync] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Sync_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Sync_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_Sync] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Sync_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_Sync_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_TranslationS Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_TranslationService];
BACKUP DATABASE [SP16PRD_TranslationService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_TranslationService_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_TranslationService_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_TranslationService] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_TranslationService_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_TranslationService_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_UsageAndHeal Recovery Model: SIMPLE
ALTER DATABASE [SP16PRD_UsageAndHealth] SET RECOVERY FULL WITH NO_WAIT;
BACKUP DATABASE [SP16PRD_UsageAndHealth] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_UsageAndHealth_backup_20181029_AGFULLX.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_UsageAndHealth_backup_20181029_AGFULLX', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_UsageAndHealth];
BACKUP DATABASE [SP16PRD_UsageAndHealth] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_UsageAndHealth_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_UsageAndHealth_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_UsageAndHealth] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_UsageAndHealth_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_UsageAndHealth_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: SP16PRD_WordAutomati Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [SP16PRD_WordAutomation];
BACKUP DATABASE [SP16PRD_WordAutomation] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_WordAutomation_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'SP16PRD_WordAutomation_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [SP16PRD_WordAutomation] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_WordAutomation_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'SP16PRD_WordAutomation_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
--Database: tpcc Recovery Model: FULL
ALTER AVAILABILITY GROUP SHAREPOINTPROD_AG ADD DATABASE [tpcc];
BACKUP DATABASE [tpcc] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\tpcc_backup_20181029_AGFULL.bak' WITH NOFORMAT, INIT, NAME = 'tpcc_backup_20181029_AGFULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
BACKUP LOG [tpcc] TO DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\tpcc_backup_20181029_AGTRAN.trn' WITH NOFORMAT, INIT, NAME = 'tpcc_backup_20181029_AGTRAN', SKIP, NOREWIND, NOUNLOAD, STATS = 10;
 
