--***********************************
-- RUN THESE COMMANDS ON THE STANDBY 
--***********************************
 
USE [master];
 
--Database: DefaultPowerPivotSer
RESTORE DATABASE [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [DefaultPowerPivotServiceApplicationDB-923e7b9c-7bd0-4b2d-b9a3-4a0146ef77d3] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: FIMSynchronizationSe
RESTORE DATABASE [FIMSynchronizationService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\FIMSynchronizationService_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [FIMSynchronizationService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\FIMSynchronizationService_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [FIMSynchronizationService] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: NW2016DB_Config
RESTORE DATABASE [NW2016DB_Config] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Config_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [NW2016DB_Config] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Config_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [NW2016DB_Config] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: NW2016DB_Content
RESTORE DATABASE [NW2016DB_Content] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Content_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [NW2016DB_Content] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Content_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [NW2016DB_Content] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: NW2016DB_Forms
RESTORE DATABASE [NW2016DB_Forms] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Forms_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [NW2016DB_Forms] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Forms_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [NW2016DB_Forms] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: NW2016DB_Temp
RESTORE DATABASE [NW2016DB_Temp] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Temp_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [NW2016DB_Temp] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\NW2016DB_Temp_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [NW2016DB_Temp] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_App_Manageme
RESTORE DATABASE [SP16PRD_App_Management] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_App_Management_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_App_Management] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_App_Management_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_App_Management] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Config
RESTORE DATABASE [SP16PRD_Config] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Config_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Config] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Config_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Config] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Appl
RESTORE DATABASE [SP16PRD_Content_Applications] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Applications_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Applications] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Applications_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Applications] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Busi
RESTORE DATABASE [SP16PRD_Content_BusinessRules] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_BusinessRules_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_BusinessRules] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_BusinessRules_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_BusinessRules] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Cent
RESTORE DATABASE [SP16PRD_Content_CentralAdmin] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CentralAdmin_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_CentralAdmin] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CentralAdmin_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_CentralAdmin] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_00] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_00_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_00] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_00_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_00] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_01] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_01_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_01] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_01_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_01] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_02] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_02_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_02] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_02_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_02] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_03] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_03_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_03] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_03_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_03] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_04] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_04_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_04] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_04_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_04] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Comm
RESTORE DATABASE [SP16PRD_Content_Community_05] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_05_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Community_05] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Community_05_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Community_05] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Corp
RESTORE DATABASE [SP16PRD_Content_CorpLibrary] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpLibrary_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_CorpLibrary] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpLibrary_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_CorpLibrary] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Corp
RESTORE DATABASE [SP16PRD_Content_CorpMediaLibrary] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_CorpMediaLibrary] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_CorpMediaLibrary_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_CorpMediaLibrary] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Digi
RESTORE DATABASE [SP16PRD_Content_DigitalWorkplace] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_DigitalWorkplace_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_DigitalWorkplace] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_DigitalWorkplace_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_DigitalWorkplace] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_MyPu
RESTORE DATABASE [SP16PRD_Content_MyPulse] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_MyPulse_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_MyPulse] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_MyPulse_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_MyPulse] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Proj
RESTORE DATABASE [SP16PRD_Content_Projects] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Projects_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Projects] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Projects_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Projects] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Content_Sear
RESTORE DATABASE [SP16PRD_Content_Search] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Search_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Content_Search] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Content_Search_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Content_Search] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_MetaData
RESTORE DATABASE [SP16PRD_MetaData] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_MetaData_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_MetaData] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_MetaData_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_MetaData] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Profile
RESTORE DATABASE [SP16PRD_Profile] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Profile_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Profile] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Profile_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Profile] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Search
RESTORE DATABASE [SP16PRD_Search] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Search] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Search] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Search_Analy
RESTORE DATABASE [SP16PRD_Search_AnalyticsReportingStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Search_AnalyticsReportingStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_AnalyticsReportingStore_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Search_AnalyticsReportingStore] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Search_Crawl
RESTORE DATABASE [SP16PRD_Search_CrawlStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_CrawlStore_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Search_CrawlStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_CrawlStore_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Search_CrawlStore] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Search_Links
RESTORE DATABASE [SP16PRD_Search_LinksStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_LinksStore_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Search_LinksStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Search_LinksStore_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Search_LinksStore] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_SecureStore
RESTORE DATABASE [SP16PRD_SecureStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SecureStore_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_SecureStore] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SecureStore_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_SecureStore] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Social
RESTORE DATABASE [SP16PRD_Social] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Social_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Social] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Social_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Social] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_StateService
RESTORE DATABASE [SP16PRD_StateService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_StateService_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_StateService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_StateService_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_StateService] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Subscription
RESTORE DATABASE [SP16PRD_SubscriptionSettings] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SubscriptionSettings_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_SubscriptionSettings] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_SubscriptionSettings_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_SubscriptionSettings] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_Sync
RESTORE DATABASE [SP16PRD_Sync] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Sync_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_Sync] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_Sync_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_Sync] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_TranslationS
RESTORE DATABASE [SP16PRD_TranslationService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_TranslationService_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_TranslationService] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_TranslationService_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_TranslationService] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_UsageAndHeal
RESTORE DATABASE [SP16PRD_UsageAndHealth] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_UsageAndHealth_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_UsageAndHealth] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_UsageAndHealth_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_UsageAndHealth] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: SP16PRD_WordAutomati
RESTORE DATABASE [SP16PRD_WordAutomation] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_WordAutomation_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [SP16PRD_WordAutomation] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\SP16PRD_WordAutomation_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [SP16PRD_WordAutomation] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
--Database: tpcc
RESTORE DATABASE [tpcc] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\tpcc_backup_20181029_AGFULL.bak' WITH NORECOVERY, STATS = 10;
RESTORE LOG [tpcc] FROM DISK='G:\SQLBackups\MSSQL13.SHAREPOINTPROD\AGInitialisation\tpcc_backup_20181029_AGTRAN.trn' WITH NORECOVERY, STATS = 10;
ALTER DATABASE [tpcc] SET HADR AVAILABILITY GROUP = SHAREPOINTPROD_AG;
 
