-- Permissions are absent in the script due to errors.
-- See exception log for details.

CREATE TABLE EDWWORK.D_MEMBER_WORK1 (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1)	NOT NULL,
  PREV_CONCAT_TEMP_STR	VARCHAR(1512),
  CONCAT_TEMP_STR	VARCHAR(1512)	NOT NULL,
  DEL_FLG	VARCHAR(1)	NOT NULL,
  ETL_DEL_FLG	VARCHAR(1)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDW_32K
  INDEX IN TBS_IDXC_EDW_32K
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK1
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = PYR;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASBIPROD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SASDIPROD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK1 TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET CURRENT SCHEMA = P1K;

