-- Permissions are absent in the script due to errors.
-- See exception log for details.

CREATE TABLE DD.DD_D_MEMBER_MASTER (
  D_MMBR_SK	INTEGER	NOT NULL,
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  GEOTRIBE_CDE	VARCHAR(20)	NOT NULL,
  GEOTRIBE_SEGMENT	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  ETL_DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_DD_16K
  INDEX IN TBS_IDXC_DD_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE DD.DD_D_MEMBER_MASTER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = PYR;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER PYR;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASBIPROD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO USER SASDIPROD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE DD.DD_D_MEMBER_MASTER TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET CURRENT SCHEMA = BDL;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,SASDIDEV1;

CREATE OR REPLACE VIEW BDL."Member Marketing Activities"
    ( "Member Number", "Communication Date", "Communication Channel", "Campaign Code", "Campaign Name",
    "Promotion Number", "Promotion Name", "Age", "Gender", "Geotribe",
    "Residential Area", "HI Policy Relationship", "Preferred Contact Method", "Document Channel", "Communications Count" )
AS
SELECT 
  MEM.MMBR_NUM,  
  CMNCN.CREATED_DT,
  CMNCN.CHAN_ID,    
  CMNCN.CMPGN_ID,  
  CMNCN.CMPGN_DESC, 
  CMNCN.PROMOTION_NUM,
  CMNCN.PROMOTION_DESC,    
  CMNCN.MMBR_AGE, 
  MEM.GENDER_CDE,
  MEM.GEOTRIBE_SEGMENT,
  NULL, -- for region Address
  CONMEM.HI_PLCY_RLTNSHP_DESC, 
  MEM.PRFRD_CONTACT_MTHD,  
  MEM.DOC_CHNL,  
  CMNCN.CMNCN_ACTIVITY_CNT
FROM
  DD.DD_F_CMNCN_ACTIVITY CMNCN
INNER JOIN DD.DD_D_MEMBER_MASTER MEM ON MEM.MMBR_NUM = CMNCN.MMBR_NUM AND CMNCN.CREATED_DT BETWEEN MEM.EFF_DT AND MEM.END_DT 
and mem.TEST_MMBR_FLG = 'N'
LEFT OUTER JOIN DD.DD_D_EN_CONTACTABLE_MEMBER CONMEM ON CONMEM.MMBR_NUM = CMNCN.MMBR_NUM AND CMNCN.CREATED_DT BETWEEN CONMEM.EFF_DT AND CONMEM.END_DT
WITH NO ROW MOVEMENT;

SET SCHEMA = PYR;

GRANT SELECT ON BDL."Member Marketing Activities" TO USER SASBIPROD;

GRANT SELECT ON BDL."Member Marketing Activities" TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON BDL."Member Marketing Activities" TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON BDL."Member Marketing Activities" TO GROUP DB2_MIS_MON;

GRANT SELECT ON BDL."Member Marketing Activities" TO GROUP EDW_SELF_SERVICE_R_PRD;

GRANT SELECT ON BDL."Member Marketing Activities" TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT SELECT ON BDL."Member Marketing Activities" TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET CURRENT SCHEMA = BDL;

CREATE OR REPLACE VIEW BDL."Member Marketing Preferences Monthly"
AS
SELECT  /*Calendar Dim*/             CAL.REPORTING_DT      as "Information Month"      /*Member Dim - more attributes might have to be added*/           , MEM.MMBR_NUM    as "Member Number"    , MEM.DATE_OF_BIRTH      as "Date of Birth"    , integer(floor((current date - MEM.DATE_OF_BIRTH)/10000)) as "Age"    , MEM.DECEASED_FLG as "Deceased Flag"    , MEM.DECEASED_DT as "Deceased Date"    , MEM.GENDER_CDE as "Gender"    , MEM.GEOTRIBE_SEGMENT as "Geotribe"    , NULL as "Residential Area"    , CONMEM.HI_PLCY_ACTIVE_FLG as "HI Policy Active Flag"    , CONMEM.HI_PLCY_APRA_FNCL_FLG as "HI APRA Financial Flag"      , CONMEM.HI_PLCY_RLTNSHP_DESC as "HI Policy Relationship"    , CONMEM.GI_HOME_MOTOR_PLCY_ACTIVE_FLG as "Home or Motor Policy Active Flag"       , CONMEM.GI_TRAVEL_12_MTH_PLCY_ACTIVE_FLG as  "Travel Policy last 12 mths Flag"    , MEM.MMBR_LATEST_SENSITIVITY_FLG as "Sensitivity flag"    , CONMEM.MMBR_CONTACTABLE_FLG as "Contactable Flag"    , CONMEM.MMBR_MARKETABLE_FLG as "Marketable Flag"    , MEM.PRFRD_CONTACT_MTHD as "Preferred Contact Method"    , MEM.DOC_CHNL as "Document Channel"    , MEM.OPT_IN_STATUS as "Opt In Status"    , MEM.HW_OPT_IN_EMAIL_STATUS as "Opt In H & W Email Flag"    , MEM.HW_OPT_IN_FACE_TO_FACE_STATUS as "Opt In H & W Face to Face Flag"    , MEM.HW_OPT_IN_MAIL_STATUS as "Opt In H & W Mail Flag"    , MEM.HW_OPT_IN_SMS_STATUS as "Opt In H & W SMS Flag"    , MEM.HW_OPT_IN_PHONE_STATUS as "Opt In H & W Phone Flag"    , MEM.GNRL_OPT_IN_EMAIL_STATUS as "Opt In General Email Flag"    , MEM.GNRL_OPT_IN_FACE_TO_FACE_STATUS as "Opt In General Face to Face Flag"    , MEM.GNRL_OPT_IN_MAIL_STATUS as "Opt In General Mail Flag"    , MEM.GNRL_OPT_IN_SMS_STATUS as "Opt In General SMS Flag"    , MEM.GNRL_OPT_IN_PHONE_STATUS as "Opt In General Phone Flag"    , decode(MEM.EMAIL_ADDR, 'Unknown', 0, 1) as "Email Flag"     , decode(MEM.MOBILE_PHONE_NUM, 'Unknown', 0, 1) as "Mobile Flag"    , decode(MEM.HOME_PHONE_NUM, 'Unknown', 0, 1) as "Home Phone Flag"    , decode(MEM.WORK_PHONE_NUM, 'Unknown', 0, 1) as "Work Phone Flag"    , MEM.MMBR_MYHBF_TERMS_ACCEPTED_FLG as "MyHBF Term Accepted Flag"    , date(MEM.MMBR_MYHBF_TERMS_ACCEPTED_TS)  as "MyHBF Term Accepted Date"    , time(MEM.MMBR_MYHBF_TERMS_ACCEPTED_TS)  as "MyHBF Term Accepted Time"    , date(MEM.MMBR_MYHBF_FIRST_LOGIN_TS)   as "MyHBF First Login Date"    , time(MEM.MMBR_MYHBF_FIRST_LOGIN_TS)   as "MyHBF First Login Time"      , date(MEM.MMBR_MYHBF_LAST_LOGIN_TS)   as "MyHBF Last Login Date"    , date(MEM.MMBR_MYHBF_LAST_LOGIN_TS)   as "MyHBF Last Login Time"  
  FROM      /*Join Member Dim to Calendar - Driving Table is Member*/      DD.DD_D_MEMBER_MASTER MEM INNER JOIN DD.DD_D_CALENDAR CAL ON CAL.REPORTING_DT BETWEEN MEM.EFF_DT AND MEM.END_DT      /*Join with Contactable Member*/      LEFT OUTER JOIN EDL.D_EN_CONTACTABLE_MEMBER CONMEM ON CONMEM.MMBR_NUM = MEM.MMBR_NUM AND CAL.REPORTING_DT BETWEEN CONMEM.EFF_DT AND CONMEM.END_DT     
  WHERE      /*Pre Join Predicate to limit Calendar Dimension*/      CALENDAR_MTH_FINISH_IND = 'Y'     AND CAL.REPORTING_DT BETWEEN DATE(TRUNC_TIMESTAMP((CURRENT TIMESTAMP - 1 DAYS) - 13 MONTHS, 'MM'))     AND (CURRENT DATE - 1 DAYS)      /* Pre Join Predicate to limit Member Dimension for the rolling 12 Months*/      AND  (  ((CURRENT DATE - 1 DAYS) BETWEEN MEM.EFF_DT AND MEM.END_DT)           OR  (DATE(TRUNC_TIMESTAMP((CURRENT TIMESTAMP - 1 DAYS) - 13 MONTHS, 'MM')) BETWEEN MEM.EFF_DT AND MEM.END_DT)          )    AND MEM.TEST_MMBR_FLG = 'N'
WITH NO ROW MOVEMENT;

SET SCHEMA = PYR;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO USER SASBIPROD;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO GROUP DB2_MIS_MON;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO GROUP EDW_SELF_SERVICE_R_PRD;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT SELECT ON BDL."Member Marketing Preferences Monthly" TO GROUP MIS_DB_ACCESS_PROD_SYS;

SET CURRENT SCHEMA = BDL;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,PYR;

CREATE OR REPLACE VIEW BDL."Member myHBF Interactions Monthly"
    ( "Information Month", "Information Date", "Member Number", "Age", "Age Group",
    "Gender", "Geotribe", "Residential Area", "HI Policy Relationship", "Sensitivity Flag",
    "Contactable Flag", "Marketable Flag", "myHBF Registered Flag", "myHBF Active Flag", "myHBF Terms Accepted Flag",
    "myHBF Terms Accepted Date", "myHBF Terms Accepted Time", "myHBF First Login Date", "myHBF First Login Time", "myHBF Last Login Date",
    "myHBF Last Login Time", "myHBF Logins Count", "Preferred Contact Method", "Document Channel", "Opt In Status",
    "Opt In H & W Email Flag", "Opt In H & W Face to Face Flag", "Opt In H & W Mail Flag", "Opt In H & W SMS Flag", "Opt In H & W Phone Flag",
    "Opt In General Email Flag", "Opt In General Face to Face Flag", "Opt In General Mail Flag", "Opt In General SMS Flag", "Opt In General Phone Flag" )
AS
SELECT     MONTHLY_FACT.REPORTING_YR_MTH,     MONTHLY_FACT.REPORTING_DT,    MEM.MMBR_NUM,    MONTHLY_FACT.MMBR_AGE,     NULL, -- Age Group
  MEM.GENDER_CDE,    MEM.GEOTRIBE_SEGMENT,    NULL, -- placehodler for address region
  CONMEM.HI_PLCY_RLTNSHP_DESC,      MEM.MMBR_LATEST_SENSITIVITY_FLG,    CONMEM.MMBR_CONTACTABLE_FLG,       CONMEM.MMBR_MARKETABLE_FLG,    MONTHLY_FACT.MMBR_MYHBF_RGSTRTN_IND,    MONTHLY_FACT.MMBR_MYHBF_ACTIVE_IND,     MONTHLY_FACT.MMBR_MYHBF_TERMS_ACCEPTED_FLG,     DATE(MONTHLY_FACT.MMBR_MYHBF_TERMS_ACCEPTED_TS),     TIME(MONTHLY_FACT.MMBR_MYHBF_TERMS_ACCEPTED_TS),      DATE(MEM.MMBR_MYHBF_FIRST_LOGIN_TS),     TIME(MEM.MMBR_MYHBF_FIRST_LOGIN_TS),     DATE(MONTHLY_FACT.LAST_LOGIN_DT),     TIME(MONTHLY_FACT.LAST_LOGIN_DT),     MONTHLY_FACT.LOGIN_ACTIVITIES_CNT,      MEM.PRFRD_CONTACT_MTHD,        MEM.DOC_CHNL,      MEM.OPT_IN_STATUS,    MEM.HW_OPT_IN_EMAIL_STATUS,    MEM.HW_OPT_IN_FACE_TO_FACE_STATUS,    MEM.HW_OPT_IN_MAIL_STATUS,    MEM.HW_OPT_IN_SMS_STATUS,    MEM.HW_OPT_IN_PHONE_STATUS,    MEM.GNRL_OPT_IN_EMAIL_STATUS,    MEM.GNRL_OPT_IN_FACE_TO_FACE_STATUS,    MEM.GNRL_OPT_IN_MAIL_STATUS,    MEM.GNRL_OPT_IN_SMS_STATUS,    MEM.GNRL_OPT_IN_PHONE_STATUS  FROM   DD.DD_MF_SUM_MYHBF_PORTAL MONTHLY_FACT  INNER JOIN DD.DD_D_MEMBER_MASTER MEM     ON MEM.MMBR_NUM = MONTHLY_FACT.MMBR_NUM   AND MONTHLY_FACT.REPORTING_DT BETWEEN MEM.EFF_DT AND MEM.END_DT   LEFT OUTER JOIN DD.DD_D_EN_CONTACTABLE_MEMBER CONMEM     ON CONMEM.MMBR_NUM = MONTHLY_FACT.MMBR_NUM   AND MONTHLY_FACT.REPORTING_DT BETWEEN CONMEM.EFF_DT AND CONMEM.END_DT
WITH NO ROW MOVEMENT;

SET SCHEMA = PYR;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO USER SASBIPROD;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO GROUP DB2_MIS_MON;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO GROUP EDW_SELF_SERVICE_R_PRD;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT SELECT ON BDL."Member myHBF Interactions Monthly" TO GROUP MIS_DB_ACCESS_PROD_SYS;

CREATE OR REPLACE ALIAS BDL_ALIAS."Member myHBF Interactions Mthly"
  FOR BDL."Member myHBF Interactions Monthly";

CREATE OR REPLACE ALIAS BDL_ALIAS."Member Marketing Pref Mthly"
  FOR BDL."Member Marketing Preferences Monthly";

CREATE UNIQUE INDEX DD.XAK1DD_DD_D_MEMBER_MASTER
  ON DD.DD_D_MEMBER_MASTER
    ( MMBR_NUM ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS;

ALTER TABLE DD.DD_D_MEMBER_MASTER
  ADD CONSTRAINT XPKDD_DD_D_MEMBER_MASTER PRIMARY KEY
    (D_MMBR_SK)
    ENFORCED;

SET CURRENT SCHEMA = P1K;

