-- Permissions are absent in the script due to errors.
-- See exception log for details.

CREATE TABLE EDL.D_MEMBER (
  D_MMBR_SK	INTEGER	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  PRFRD_CONTACT_MTHD	VARCHAR(100)	NOT NULL,
  DOC_CHNL	VARCHAR(100)	NOT NULL,
  EMAIL_ADDR	VARCHAR(1024)	NOT NULL,
  HOME_PHONE_NUM	VARCHAR(50)	NOT NULL,
  MOBILE_PHONE_NUM	VARCHAR(50)	NOT NULL,
  WORK_PHONE_NUM	VARCHAR(50)	NOT NULL,
  OPT_IN_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50)	NOT NULL,
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_LATEST_SENSITIVITY_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  EFF_DT	DATE	NOT NULL,
  END_DT	DATE	NOT NULL,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  ETL_DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDL_16K
  INDEX IN TBS_IDXC_EDL_16K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDL.D_MEMBER
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = PYR;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SASBIPROD;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO USER SASDIPROD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDL.D_MEMBER TO GROUP MIS_DB_ACCESS_PROD_SYS;

CREATE UNIQUE INDEX EDL.XAK1D_MEMBER
  ON EDL.D_MEMBER
    ( MMBR_NUM ASC, EFF_DT ASC )
  ALLOW REVERSE SCANS
  COMPRESS YES
  INCLUDE NULL KEYS
  COLLECT STATISTICS;

ALTER TABLE EDL.D_MEMBER
  ADD CONSTRAINT XPKD_MEMBER PRIMARY KEY
    (D_MMBR_SK)
    ENFORCED;

SET CURRENT SCHEMA = P1K;

