DROP TABLE EDWWORK.D_MEMBER_WORK_CHANGES;

CREATE TABLE EDWWORK.D_MEMBER_WORK_CHANGES (
  MMBR_NUM	VARCHAR(20),
  EFF_DT	DATE,
  END_DT	DATE,
  PRFRD_CONTACT_MTHD	VARCHAR(100),
  DOC_CHNL	VARCHAR(100),
  EMAIL_ADDR	VARCHAR(1024),
  HOME_PHONE_NUM	VARCHAR(50),
  MOBILE_PHONE_NUM	VARCHAR(50),
  WORK_PHONE_NUM	VARCHAR(50),
  OPT_IN_STATUS	VARCHAR(50),
  HW_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  HW_OPT_IN_MAIL_STATUS	VARCHAR(50),
  HW_OPT_IN_SMS_STATUS	VARCHAR(50),
  HW_OPT_IN_PHONE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_EMAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_FACE_TO_FACE_STATUS	VARCHAR(50),
  GNRL_OPT_IN_MAIL_STATUS	VARCHAR(50),
  GNRL_OPT_IN_SMS_STATUS	VARCHAR(50),
  GNRL_OPT_IN_PHONE_STATUS	VARCHAR(50),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1),
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1),
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1),
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1),
  DEL_FLG	VARCHAR(1),
  ETL_DEL_FLG	VARCHAR(1),
  INSERT_BATCH_AUDIT_SK	DECIMAL(11, 0),
  UPDATE_BATCH_AUDIT_SK	DECIMAL(11, 0),
  INSERT_TS	TIMESTAMP,
  UPDATE_TS	TIMESTAMP
  ) 
  IN USERSPACE1
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK_CHANGES
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_MEMBER_WORK_CHANGES TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET CURRENT SCHEMA = P1K;

