-- Permissions are absent in the script due to errors.
-- See exception log for details.

CREATE TABLE EDWWORK.D_MEMBER_WORK_MM (
  MMBR_NUM	VARCHAR(20),
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	VARCHAR(1),
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(20),
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	VARCHAR(1),
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  TEST_MMBR_FLG	VARCHAR(1),
  MMBR_LATEST_SENSITIVITY_FLG	VARCHAR(1),
  CHANGE_FLG	VARCHAR(1),
  DEL_FLG	VARCHAR(1),
  ETL_DEL_FLG	VARCHAR(1),
  UPDATE_BATCH_AUDIT_SK	DOUBLE,
  UPDATE_TS	TIMESTAMP,
  MODIFIED_SRC_TABLES	VARCHAR(500),
  INSERT_TS	TIMESTAMP
  ) 
  IN TBS_BASE_RFID_04K
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_MEMBER_WORK_MM
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

