CREATE TABLE EDWWORK.D_W_MEMBER_LATEST_WORK (
  MMBR_NUM	VARCHAR(20)	NOT NULL,
  DATE_OF_BIRTH	DATE,
  DECEASED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  DECEASED_DT	DATE,
  GENDER_CDE	VARCHAR(10)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  MMBR_MYHBF_TERMS_ACCEPTED_TS	TIMESTAMP,
  MMBR_MYHBF_FIRST_LOGIN_TS	TIMESTAMP,
  MMBR_MYHBF_LAST_LOGIN_TS	TIMESTAMP,
  DEL_FLG	CHARACTER(1 OCTETS)	NOT NULL,
  INSERT_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  UPDATE_BATCH_AUDIT_SK	INTEGER	NOT NULL,
  INSERT_TS	TIMESTAMP	NOT NULL,
  UPDATE_TS	TIMESTAMP	NOT NULL
  ) 
  IN TBS_BASEC_EDW_32K
  INDEX IN TBS_IDXC_EDW_32K
  COMPRESS YES ADAPTIVE
  VALUE COMPRESSION
  ORGANIZE BY ROW;

ALTER TABLE EDWWORK.D_W_MEMBER_LATEST_WORK
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

SET SCHEMA = GZD;

GRANT SELECT ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO USER SASDIDEV1;

GRANT SELECT ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO GROUP DB2_MIS_MON;

GRANT SELECT ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TABLE EDWWORK.D_W_MEMBER_LATEST_WORK TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET CURRENT SCHEMA = P1K;

