--DB_RDSR
SET CURRENT SCHEMA = GZD;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,GZD;

CREATE OR REPLACE VIEW CGUGI.SEM_CGU_GI_SALE_V
AS
SELECT SALES.ORIGINAL_REPORTING_DT AS "Processed Date", COALESCE(MORG.GROUP_L2_DESC,'Unknown') AS "Group", COALESCE(MORG.DIVISION_L3_DESC,'Unknown') AS "Division", COALESCE(MORG.DEPT_L4_DESC,'Unknown') AS "Department", COALESCE(MORG.SUB_DEPT_L5_DESC,'Unknown') AS "Sub Department", COALESCE(MORG.BRANCH_L6_DESC,'Unknown') AS "Branch Area", COALESCE(MORG.TEAM_L7_ID,'UNK') AS "Team ID", COALESCE(MORG.TEAM_L7_DESC,'Unknown') AS "Team Name", SALES.ENTITY AS "Entity", SALES.CHANNEL AS "Channel", DDPCOMP.PROD_CLASS_L3_DESC AS "Product Class", SALES.RISK_TYPE AS "Product Group", 'ACQUISITION' AS "Sale Type", SUM(SALE_CNT) AS "GI Financial Sales" 
  FROM CGUGI.SEM_CGU_GI_NET_SALE SALES LEFT OUTER JOIN WAREHOUSE.NICKNAME_DD_D_MGMT_ORG MORG ON MORG.TEAM_L7_ID = (CASE WHEN SALES.CHANNEL='Internet' THEN '1136' ELSE COALESCE(SALES.HBF_TEAM_ID,'UNK') 
  END) AND MORG.MGMT_LVL_NO = 7 AND MORG.GROUP_L2_ID = '1002' INNER JOIN WAREHOUSE.NICKNAME_DD_D_PRODUCT_COMP DDPCOMP ON SALES.PROD_CLASS_L3_ID = DDPCOMP.PROD_CLASS_L3_ID AND DDPCOMP.LVL_NO = 3 
  WHERE YEAR(SALES.ORIGINAL_REPORTING_DT) >= YEAR(CURRENT DATE) -5 GROUP BY SALES.ORIGINAL_REPORTING_DT, COALESCE(MORG.GROUP_L2_DESC,'Unknown'), COALESCE(MORG.DIVISION_L3_DESC,'Unknown'), COALESCE(MORG.DEPT_L4_DESC,'Unknown'), COALESCE(MORG.SUB_DEPT_L5_DESC,'Unknown'), COALESCE(MORG.BRANCH_L6_DESC,'Unknown'), COALESCE(MORG.TEAM_L7_ID,'UNK'), COALESCE(MORG.TEAM_L7_DESC,'Unknown'), SALES.ENTITY, SALES.CHANNEL, DDPCOMP.PROD_CLASS_L3_DESC, SALES.RISK_TYPE, 'ACQUISITION'
WITH NO ROW MOVEMENT;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASBIRLSE;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SASDIRLSE;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP DB2_MIS_MON;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP MIS_ROLE_VIABILITY;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_BI;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_BUS;

GRANT SELECT ON CGUGI.SEM_CGU_GI_SALE_V TO GROUP RDS_DB_ACCESS_RLSE_R;

SET CURRENT SCHEMA = P1K;

SET CURRENT SCHEMA = GZD;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,GZD;

--DB_EDWDR
CREATE OR REPLACE VIEW DD.SEM_QUOTES_SALE_TARGET_V
AS
SELECT CAL.REPORTING_DT AS "Processed Date", GROUP_L2_DESC AS "Group", DIVISION_L3_DESC AS "Division", DEPT_L4_DESC AS "Department", SUB_DEPT_L5_DESC AS "Sub Department", BRANCH_L6_DESC AS "Branch Area", MORG.TEAM_L7_ID AS "Team ID", MORG.TEAM_L7_DESC AS "Team Name", DDPCOMP.ENTITY_L2_ID AS "Entity", CHNL.CHANNEL_CDE AS "Channel", DDPCOMP.PROD_CLASS_L3_DESC AS "Product Class", DDPCOMP.PROD_GRP_L4_DESC AS "Product Group", 'ACQUISITION' AS "Sale Type", SUM(CASE FSALE.ROW_TYP WHEN 'Q' THEN TRGT_SALE_CNT ELSE 0 
  END) AS "Target Quote Counts", SUM(CASE FSALE.ROW_TYP WHEN 'S' THEN TRGT_SALE_CNT ELSE 0 
  END) AS "Target Sale Counts" 
  FROM DD.DD_F_SALE_TARGET FSALE INNER JOIN DD.DD_D_CALENDAR CAL ON CAL.D_CALENDAR_SK = FSALE.D_CALENDAR_SK INNER JOIN DD.DD_D_MGMT_ORG MORG ON MORG.D_MGMT_ORG_SK = FSALE.D_MGMT_ORG_SK INNER JOIN DD.DD_D_PRODUCT_COMP DDPCOMP ON DDPCOMP.D_PROD_COMP_SK = FSALE.D_PROD_COMP_SK INNER JOIN DD.DD_D_CHANNEL CHNL ON CHNL.D_CHANNEL_SK = FSALE.D_CHANNEL_SK INNER JOIN DD.DD_D_POLICY_EVENT POLEVE ON POLEVE.D_PLCY_EVNT_SK = FSALE.D_PLCY_EVNT_SK 
  WHERE YEAR(CAL.REPORTING_DT) >= YEAR(CURRENT DATE - 5 YEARS) AND ENTITY_L2_ID IN ('HI','GI') AND NOT(ENTITY_L2_ID IN ('HI') AND CHNL.CHANNEL_CDE = 'Internet' AND FSALE.ROW_TYP = 'Q') GROUP BY CAL.REPORTING_DT, MORG.MASTER_L1_DESC, MORG.GROUP_L2_DESC, MORG.DIVISION_L3_DESC, MORG.DEPT_L4_DESC, MORG.SUB_DEPT_L5_DESC, MORG.BRANCH_L6_DESC, MORG.TEAM_L7_ID, MORG.TEAM_L7_DESC, DDPCOMP.ENTITY_L2_ID, CHNL.CHANNEL_CDE, DDPCOMP.PROD_CLASS_L3_DESC, DDPCOMP.PROD_GRP_L4_DESC, 'ACQUISITION' 
  UNION ALL 
  SELECT CAL.REPORTING_DT AS "Processed Date", GROUP_L2_DESC AS "Group", DIVISION_L3_DESC AS "Division", DEPT_L4_DESC AS "Department", SUB_DEPT_L5_DESC AS "Sub Department", BRANCH_L6_DESC AS "Branch Area", MORG.TEAM_L7_ID AS "Team ID", MORG.TEAM_L7_DESC AS "Team Name", DDPCOMP.ENTITY_L2_ID AS "Entity", CHNL.CHANNEL_CDE AS "Channel", 'Unknown' AS "Product Class", 'Unknown' AS "Product Group", 'ACQUISITION' AS "Sale Type", ( MAX(CASE FSALE.ROW_TYP WHEN 'Q' THEN TRGT_SALE_CNT ELSE 0 
  END) ) AS "Target Quote Counts", 0 AS "Target Sale Counts" 
  FROM DD.DD_F_SALE_TARGET FSALE INNER JOIN DD.DD_D_CALENDAR CAL ON CAL.D_CALENDAR_SK = FSALE.D_CALENDAR_SK INNER JOIN DD.DD_D_MGMT_ORG MORG ON MORG.D_MGMT_ORG_SK = FSALE.D_MGMT_ORG_SK INNER JOIN DD.DD_D_PRODUCT_COMP DDPCOMP ON DDPCOMP.D_PROD_COMP_SK = FSALE.D_PROD_COMP_SK INNER JOIN DD.DD_D_CHANNEL CHNL ON CHNL.D_CHANNEL_SK = FSALE.D_CHANNEL_SK INNER JOIN DD.DD_D_POLICY_EVENT POLEVE ON POLEVE.D_PLCY_EVNT_SK = FSALE.D_PLCY_EVNT_SK 
  WHERE YEAR(CAL.REPORTING_DT) >= YEAR(CURRENT DATE - 5 YEARS) AND ENTITY_L2_ID IN ('HI') AND CHNL.CHANNEL_CDE = 'Internet' AND FSALE.ROW_TYP = 'Q' GROUP BY CAL.REPORTING_DT, MORG.MASTER_L1_DESC, MORG.GROUP_L2_DESC, MORG.DIVISION_L3_DESC, MORG.DEPT_L4_DESC, MORG.SUB_DEPT_L5_DESC, MORG.BRANCH_L6_DESC, MORG.TEAM_L7_ID, MORG.TEAM_L7_DESC, DDPCOMP.ENTITY_L2_ID, CHNL.CHANNEL_CDE
WITH NO ROW MOVEMENT;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO USER SASDIDEV1;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO GROUP DB2_MIS_MON;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO GROUP MIS_DB_ACCESS_PROD_SYS;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON DD.SEM_QUOTES_SALE_TARGET_V TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET CURRENT SCHEMA = P1K;

SET CURRENT SCHEMA = GZD;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,GZD;

CREATE OR REPLACE VIEW DD.SEM_HI_SALE_V
AS
SELECT CAL.REPORTING_DT AS "Processed Date", GROUP_L2_DESC AS "Group", DIVISION_L3_DESC AS "Division", DEPT_L4_DESC AS "Department", SUB_DEPT_L5_DESC AS "Sub Department", BRANCH_L6_DESC AS "Branch Area", MORG.TEAM_L7_ID AS "Team ID", MORG.TEAM_L7_DESC AS "Team Name", DDPCOMP.ENTITY_L2_ID AS "Entity", CHNL.CHANNEL_CDE AS "Channel", DDPCOMP.PROD_CLASS_L3_DESC AS "Product Class", DDPCOMP.PROD_GRP_L4_DESC AS "Product Group", POLEVE.PLCY_EVNT_TYP_DESC AS "Sale Type", SUM(CASE POLEVE.PLCY_EVNT_CAT_ID WHEN 1 THEN SALE_CNT ELSE 0   
  END) AS "HI Pending Sales", SUM(CASE POLEVE.PLCY_EVNT_CAT_ID WHEN 2 THEN SALE_CNT ELSE 0   
  END) AS "HI Financial Sales" 
  FROM DD.DD_F_SALE FSALE INNER JOIN DD.DD_D_CALENDAR CAL ON CAL.D_CALENDAR_SK = FSALE.D_CALENDAR_SALE_SK INNER JOIN DD.DD_D_MGMT_ORG MORG ON MORG.D_MGMT_ORG_SK = FSALE.D_MGMT_ORG_SALE_SK INNER JOIN DD.DD_D_PRODUCT_COMP DDPCOMP ON DDPCOMP.D_PROD_COMP_SK = FSALE.D_PROD_COMP_SK INNER JOIN DD.DD_D_CHANNEL CHNL ON CHNL.D_CHANNEL_SK = FSALE.D_CHANNEL_SK INNER JOIN DD.DD_D_POLICY_EVENT POLEVE ON POLEVE.D_PLCY_EVNT_SK = FSALE.D_PLCY_EVNT_SK 
  WHERE YEAR(CAL.REPORTING_DT) >= YEAR(CURRENT DATE - 5 YEARS) AND POLEVE.PLCY_EVNT_CAT_ID IN ('1','2') AND ENTITY_L2_ID = 'HI' GROUP BY CAL.REPORTING_DT, MORG.MASTER_L1_DESC, MORG.GROUP_L2_DESC, MORG.DIVISION_L3_DESC, MORG.DEPT_L4_DESC, MORG.SUB_DEPT_L5_DESC, MORG.BRANCH_L6_DESC, MORG.TEAM_L7_ID, MORG.TEAM_L7_DESC, DDPCOMP.ENTITY_L2_ID, CHNL.CHANNEL_CDE, DDPCOMP.PROD_CLASS_L3_DESC, DDPCOMP.PROD_GRP_L4_DESC, POLEVE.PLCY_EVNT_TYP_DESC
WITH NO ROW MOVEMENT;

GRANT SELECT ON DD.SEM_HI_SALE_V TO USER SASDIDEV1;

GRANT SELECT ON DD.SEM_HI_SALE_V TO USER SVC_BI_FEDDBUSER_PRD;

GRANT SELECT ON DD.SEM_HI_SALE_V TO USER SVC_BI_FEDDBUSER_RLS;

GRANT SELECT ON DD.SEM_HI_SALE_V TO USER SVC_TBLADMIN_PRD;

GRANT SELECT ON DD.SEM_HI_SALE_V TO USER SVC_TBLADMIN_RLS;

GRANT SELECT ON DD.SEM_HI_SALE_V TO GROUP DB2_MIS_MON;

GRANT SELECT ON DD.SEM_HI_SALE_V TO GROUP MIS_DB_ACCESS_PROD_R;

GRANT SELECT ON DD.SEM_HI_SALE_V TO GROUP MIS_DB_ACCESS_PROD_SYS;

GRANT SELECT ON DD.SEM_HI_SALE_V TO GROUP MIS_DB_ACCESS_RLSE_R;

GRANT SELECT ON DD.SEM_HI_SALE_V TO GROUP MIS_DB_ACCESS_RLSE_SYS;

SET CURRENT SCHEMA = P1K;

