SELECT DISTINCT J.GROUP_NAME, J.MEMNAME, P.CONDITION
FROM       dbo.DEF_VER_JOB    J 
INNER JOIN dbo.DEF_VER_LNKI_P P 
  ON  J.TABLE_ID = P.TABLE_ID
  AND J.JOB_ID   = P.JOB_ID
WHERE J.MEMNAME    IS NOT NULL
  AND J.GROUP_NAME IS NOT NULL
  AND J.MEMNAME    <> ' '
  AND J.GROUP_NAME <> ' '
  AND J.NODE_ID     = ' '
ORDER BY J.GROUP_NAME, J.MEMNAME, P.CONDITION
