SELECT B.JOBNAME
, B.NODEID
, B.MESSAGE
, A.START_TIME
, A.END_TIME
--, CONVERT (time, A.END_TIME - A.START_TIME) AS ELAPSED, B.LOGTIME
--, CONVERT (date, CONCAT ( SUBSTRING(B.LOGDATE,1,4) , '-' , SUBSTRING(B.LOGDATE,5,2) , '-' , SUBSTRING(B.LOGDATE,7,2) ) ) AS LOG_DATE
--, CONVERT (time, CONCAT ( SUBSTRING(B.LOGTIME,1,2) , ':' , SUBSTRING(B.LOGTIME,3,2) , ':' , SUBSTRING(B.LOGTIME,5,2) ) ) AS LOG_TIME
--, CONVERT (datetime, CONCAT ( SUBSTRING(B.LOGDATE,1,4) , '-' , SUBSTRING(B.LOGDATE,5,2) , '-' , SUBSTRING(B.LOGDATE,7,2) , ' ', SUBSTRING(B.LOGTIME,1,2) , ':' , SUBSTRING(B.LOGTIME,3,2) , ':' , SUBSTRING(B.LOGTIME,5,2) ) ) AS LOG_TIMESTAMP
, CONVERT (time, A.START_TIME - (CONVERT (datetime, CONCAT ( SUBSTRING(B.LOGDATE,1,4) , '-' , SUBSTRING(B.LOGDATE,5,2) , '-' , SUBSTRING(B.LOGDATE,7,2) , ' ', SUBSTRING(B.LOGTIME,1,2) , ':' , SUBSTRING(B.LOGTIME,3,2) , ':' , SUBSTRING(B.LOGTIME,5,2) ) ) ) ) AS LOG_WAIT_TIME
FROM [em800].[dbo].[RUNINFO_HISTORY] A
INNER JOIN
[ctrlm800].[dbo].[CMR_IOALOG_1] B ON B.[JOBNAME] = A.JOB_MEM_NAME
WHERE B.MESSAGE LIKE 'Job STATE CHANGED TO Wait Resource'
AND B.NODEID like 'sasdevcomp'
AND CONVERT( date, A.START_TIME) = CONVERT (date, CURRENT_TIMESTAMP)  
ORDER BY A.START_TIME